// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void logoanimation_Animation(lv_obj_t * TargetObject, int delay);
void shortCutAnimation_Animation(lv_obj_t * TargetObject, int delay);
void loadingView_Animation(lv_obj_t * TargetObject, int delay);
void refView_Animation(lv_obj_t * TargetObject, int delay);
void alarmAnimation_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenLogo
void ui_ScreenLogo_screen_init(void);
void ui_event_ScreenLogo(lv_event_t * e);
lv_obj_t * ui_ScreenLogo;
lv_obj_t * ui_Imagelogo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain(lv_event_t * e);
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_ContainerTime;
lv_obj_t * ui_LabelHour;
lv_obj_t * ui_LabelMaoHao;
lv_obj_t * ui_LabelMin;
lv_obj_t * ui_ContainerDate;
lv_obj_t * ui_LabelDate;
lv_obj_t * ui_LabelDouHao;
lv_obj_t * ui_LabelWeek;
lv_obj_t * ui_ContainerIconList;
lv_obj_t * ui_ContainerIcon;
void ui_event_ContainerIcon_ImgButtonIcon(lv_event_t * e);
lv_obj_t * ui_ContainerIcon2;
void ui_event_ContainerIcon2_ImgButtonIcon(lv_event_t * e);
lv_obj_t * ui_ContainerIcon3;
void ui_event_ContainerIcon3_ImgButtonIcon(lv_event_t * e);
lv_obj_t * ui_ContainerIcon4;
void ui_event_ContainerIcon4_ImgButtonIcon(lv_event_t * e);
void ui_event_ContainerShortCutMain_ContainerShortCut(lv_event_t * e);
lv_obj_t * ui_ContainerShortCutMain;
void ui_event_ContainerShortCutMain_ImgButtonSetting(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonClock(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonBiaoPan(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonWeather(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonUpdate(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonAbour(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonzhuye(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenShutCut
void ui_ScreenShutCut_screen_init(void);
lv_obj_t * ui_ScreenShutCut;
lv_obj_t * ui_ContainerShortCut;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenUpdate
void ui_ScreenUpdate_screen_init(void);
lv_obj_t * ui_ScreenUpdate;
void ui_event_ImgButtonClose(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose;
lv_obj_t * ui_LabelTitleUpdate;
lv_obj_t * ui_LabelUpdateTip;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_LabelProgress;
void ui_event_ImgButtonUpdate(lv_event_t * e);
lv_obj_t * ui_ImgButtonUpdate;
lv_obj_t * ui_Label4;
void ui_event_ImgButtonUpdateCancel(lv_event_t * e);
lv_obj_t * ui_ImgButtonUpdateCancel;
lv_obj_t * ui_Label1;
lv_obj_t * ui_LabelUpdateTip2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenClock
void ui_ScreenClock_screen_init(void);
void ui_event_ScreenClock(lv_event_t * e);
lv_obj_t * ui_ScreenClock;
lv_obj_t * ui_Container1;
lv_obj_t * ui_LabelClockHour;
lv_obj_t * ui_Label6;
lv_obj_t * ui_LabelClockMin;
lv_obj_t * ui_Label8;
lv_obj_t * ui_LabelClockSec;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
lv_obj_t * ui_ScreenWeather;
void ui_event_ImgButtonClose2(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose2;
lv_obj_t * ui_Image9;
lv_obj_t * ui_LabelWeatherLocation;
lv_obj_t * ui_Container2;
lv_obj_t * ui_ImageWeatherToday;
lv_obj_t * ui_LabelTempTpday;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label36;
lv_obj_t * ui_LabelWindText;
lv_obj_t * ui_Label38;
lv_obj_t * ui_LabelWind;
lv_obj_t * ui_Label39;
lv_obj_t * ui_LabelHBA;
lv_obj_t * ui_Container3;
lv_obj_t * ui_ContainerWeatherComp;
lv_obj_t * ui_LabelWeatherTime;
lv_obj_t * ui_ImageWeatherIcon;
lv_obj_t * ui_LabelTempValue;
lv_obj_t * ui_Image11;
lv_obj_t * ui_LabelHumValue;
lv_obj_t * ui_ContainerWeatherComp1;
lv_obj_t * ui_LabelWeatherTime2;
lv_obj_t * ui_ImageWeatherIcon2;
lv_obj_t * ui_LabelTempValue2;
lv_obj_t * ui_Image20;
lv_obj_t * ui_LabelHumValue2;
lv_obj_t * ui_ContainerWeatherComp2;
lv_obj_t * ui_LabelWeatherTime3;
lv_obj_t * ui_ImageWeatherIcon3;
lv_obj_t * ui_LabelTempValue3;
lv_obj_t * ui_Image21;
lv_obj_t * ui_LabelHumValue3;
lv_obj_t * ui_ContainerWeatherComp3;
lv_obj_t * ui_LabelWeatherTime4;
lv_obj_t * ui_ImageWeatherIcon4;
lv_obj_t * ui_LabelTempValue4;
lv_obj_t * ui_Image22;
lv_obj_t * ui_LabelHumValue4;
lv_obj_t * ui_ContainerWeatherComp4;
lv_obj_t * ui_LabelWeatherTime5;
lv_obj_t * ui_ImageWeatherIcon5;
lv_obj_t * ui_LabelTempValue5;
lv_obj_t * ui_Image23;
lv_obj_t * ui_LabelHumValue5;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAlarmClock
void ui_ScreenAlarmClock_screen_init(void);
void ui_event_ScreenAlarmClock(lv_event_t * e);
lv_obj_t * ui_ScreenAlarmClock;
void ui_event_ImgButtonClose3(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_ContainerNoData;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label32;
lv_obj_t * ui_ContainerClockList;
void ui_event_ImgButtonAddClock(lv_event_t * e);
lv_obj_t * ui_ImgButtonAddClock;
lv_obj_t * ui_ContainerSelectTime;
void ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonCancel(lv_event_t * e);
void ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonSure(lv_event_t * e);
lv_obj_t * ui_ContainerDialog;
void ui_event_ContainerDialog_Container25_Container27_ButtonCancelDelete(lv_event_t * e);
void ui_event_ContainerDialog_Container25_Container27_ButtonSureDelete(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAbout
void ui_ScreenAbout_screen_init(void);
lv_obj_t * ui_ScreenAbout;
void ui_event_ImgButtonClose4(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose4;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label5;
lv_obj_t * ui_LabelProjrctName;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label13;
lv_obj_t * ui_LabelProjrctVersion;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Container14;
void ui_event_Container11(lv_event_t * e);
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Image12;
void ui_event_Container13(lv_event_t * e);
lv_obj_t * ui_Container13;
lv_obj_t * ui_Image13;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
lv_obj_t * ui_ScreenSetting;
void ui_event_ImgButtonClose5(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose5;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Container15;
lv_obj_t * ui_ContainerWifiSetting;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Container18;
lv_obj_t * ui_Label18;
lv_obj_t * ui_LabelWiFiName;
lv_obj_t * ui_Container19;
lv_obj_t * ui_Label19;
lv_obj_t * ui_LabelWiFiPassword;
lv_obj_t * ui_Container20;
lv_obj_t * ui_Label20;
lv_obj_t * ui_LabelWiFiStatus;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_ContainerMqttSetting;
lv_obj_t * ui_Container21;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label21;
void ui_event_SwitchMQTT(lv_event_t * e);
lv_obj_t * ui_SwitchMQTT;
lv_obj_t * ui_Container22;
lv_obj_t * ui_Label22;
lv_obj_t * ui_LabelMqttUrl;
lv_obj_t * ui_Container23;
lv_obj_t * ui_Label23;
lv_obj_t * ui_LabelMqttPort;
lv_obj_t * ui_Container24;
lv_obj_t * ui_Label24;
lv_obj_t * ui_LabelMqttStatus;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWiFiSetting
void ui_ScreenWiFiSetting_screen_init(void);
void ui_event_ScreenWiFiSetting(lv_event_t * e);
lv_obj_t * ui_ScreenWiFiSetting;
void ui_event_ImgButtonClose6(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose6;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Container17;
lv_obj_t * ui_RollerWiFiSelect;
void ui_event_ButtonWiFiSure(lv_event_t * e);
lv_obj_t * ui_ButtonWiFiSure;
lv_obj_t * ui_Label17;
void ui_event_ImageRefView(lv_event_t * e);
lv_obj_t * ui_ImageRefView;
lv_obj_t * ui_ContainerLoading2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWiFiPassword
void ui_ScreenWiFiPassword_screen_init(void);
void ui_event_ScreenWiFiPassword(lv_event_t * e);
lv_obj_t * ui_ScreenWiFiPassword;
void ui_event_ImgButtonClose7(lv_event_t * e);
lv_obj_t * ui_ImgButtonClose7;
lv_obj_t * ui_Label27;
void ui_event_TextAreaPassword(lv_event_t * e);
lv_obj_t * ui_TextAreaPassword;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_Label29;
lv_obj_t * ui_selectWifiName;
void ui_event_ButtonWiFiSure2(lv_event_t * e);
lv_obj_t * ui_ButtonWiFiSure2;
lv_obj_t * ui_Label28;
lv_obj_t * ui_ContainerLoading3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen404
void ui_Screen404_screen_init(void);
lv_obj_t * ui_Screen404;
lv_obj_t * ui_Image18;
void ui_event_ImgButtonRestWfi(lv_event_t * e);
lv_obj_t * ui_ImgButtonRestWfi;
lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAlarm
void ui_ScreenAlarm_screen_init(void);
void ui_event_ScreenAlarm(lv_event_t * e);
lv_obj_t * ui_ScreenAlarm;
lv_obj_t * ui_ImageAlarm;
lv_obj_t * ui_Label30;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0(lv_event_t * e);
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void logoanimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 6000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_set_ready_cb(&PropertyAnimation_0, logoAnim_end_cb); 
    lv_anim_start(&PropertyAnimation_0);

}
void shortCutAnimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 400, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 2000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 100, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_1);

}
void loadingView_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 2000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}
void refView_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 3600, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 2);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void alarmAnimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_flag_modify(ui_Imagelogo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_opacity_set(ui_Imagelogo, 0);
    }
}

void ui_event_ScreenMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ContainerIcon_ImgButtonIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenWeather_screen_init);
    }
}

void ui_event_ContainerIcon2_ImgButtonIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAlarmClock, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenAlarmClock_screen_init);
    }
}

void ui_event_ContainerIcon3_ImgButtonIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenClock, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenClock_screen_init);
    }
}

void ui_event_ContainerIcon4_ImgButtonIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenSetting_screen_init);
    }
}

void ui_event_ContainerShortCutMain_ContainerShortCut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonBiaoPan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonAbour(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerShortCutMain_ImgButtonzhuye(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerShortCutMain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ImgButtonClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ImgButtonUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ImgButtonUpdateCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ScreenClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenMain_screen_init);
        clicked_callback(e);
    }
}

void ui_event_ImgButtonClose2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ScreenAlarmClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clicked_callback(e);
    }
}

void ui_event_ImgButtonClose3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ImgButtonAddClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerSelectTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerSelectTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonSure(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ContainerDialog_Container25_Container27_ButtonCancelDelete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ContainerDialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        clicked_callback(e);
    }
}

void ui_event_ContainerDialog_Container25_Container27_ButtonSureDelete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ImgButtonClose4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_Container11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Container13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Container13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Container13, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ImgButtonClose5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWiFiSetting, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenWiFiSetting_screen_init);
        clicked_callback(e);
    }
}

void ui_event_SwitchMQTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_callback(e);
    }
}

void ui_event_ScreenWiFiSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        loadingView_Animation(ui_comp_get_child(ui_ContainerLoading2, UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_IMAGE15),
                              0);
    }
}

void ui_event_ImgButtonClose6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ButtonWiFiSure(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ImageRefView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
        refView_Animation(ui_ImageRefView, 0);
        _ui_flag_modify(ui_ContainerLoading2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ScreenWiFiPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        loadingView_Animation(ui_comp_get_child(ui_ContainerLoading3, UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_IMAGE15),
                              0);
    }
}

void ui_event_ImgButtonClose7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWiFiSetting, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenWiFiSetting_screen_init);
    }
}

void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextAreaPassword);
    }
}

void ui_event_ButtonWiFiSure2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ImgButtonRestWfi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event_ScreenAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        alarmAnimation_Animation(ui_ImageAlarm, 0);
        alarmAnimation_Animation(ui_Label30, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

void ui_event____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        logoanimation_Animation(ui_Imagelogo, 400);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLogo_screen_init();
    ui_ScreenMain_screen_init();
    ui_ScreenShutCut_screen_init();
    ui_ScreenUpdate_screen_init();
    ui_ScreenClock_screen_init();
    ui_ScreenWeather_screen_init();
    ui_ScreenAlarmClock_screen_init();
    ui_ScreenAbout_screen_init();
    ui_ScreenSetting_screen_init();
    ui_ScreenWiFiSetting_screen_init();
    ui_ScreenWiFiPassword_screen_init();
    ui_Screen404_screen_init();
    ui_ScreenAlarm_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

    lv_disp_load_scr(ui____initial_actions0);
    lv_disp_load_scr(ui_ScreenLogo);
}
