// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void logoanimation_Animation(lv_obj_t * TargetObject, int delay);
void shortCutAnimation_Animation(lv_obj_t * TargetObject, int delay);
void loadingView_Animation(lv_obj_t * TargetObject, int delay);
void refView_Animation(lv_obj_t * TargetObject, int delay);
void alarmAnimation_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenLogo
void ui_ScreenLogo_screen_init(void);
void ui_event_ScreenLogo(lv_event_t * e);
extern lv_obj_t * ui_ScreenLogo;
extern lv_obj_t * ui_Imagelogo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain(lv_event_t * e);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_ContainerTime;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelMaoHao;
extern lv_obj_t * ui_LabelMin;
extern lv_obj_t * ui_ContainerDate;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelDouHao;
extern lv_obj_t * ui_LabelWeek;
extern lv_obj_t * ui_ContainerIconList;
extern lv_obj_t * ui_ContainerIcon;
void ui_event_ContainerIcon_ImgButtonIcon(lv_event_t * e);
extern lv_obj_t * ui_ContainerIcon2;
void ui_event_ContainerIcon2_ImgButtonIcon(lv_event_t * e);
extern lv_obj_t * ui_ContainerIcon3;
void ui_event_ContainerIcon3_ImgButtonIcon(lv_event_t * e);
extern lv_obj_t * ui_ContainerIcon4;
void ui_event_ContainerIcon4_ImgButtonIcon(lv_event_t * e);
void ui_event_ContainerShortCutMain_ContainerShortCut(lv_event_t * e);
extern lv_obj_t * ui_ContainerShortCutMain;
void ui_event_ContainerShortCutMain_ImgButtonSetting(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonClock(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonBiaoPan(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonWeather(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonUpdate(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonAbour(lv_event_t * e);
void ui_event_ContainerShortCutMain_ImgButtonzhuye(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenShutCut
void ui_ScreenShutCut_screen_init(void);
extern lv_obj_t * ui_ScreenShutCut;
extern lv_obj_t * ui_ContainerShortCut;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenUpdate
void ui_ScreenUpdate_screen_init(void);
extern lv_obj_t * ui_ScreenUpdate;
void ui_event_ImgButtonClose(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose;
extern lv_obj_t * ui_LabelTitleUpdate;
extern lv_obj_t * ui_LabelUpdateTip;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_LabelProgress;
void ui_event_ImgButtonUpdate(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonUpdate;
extern lv_obj_t * ui_Label4;
void ui_event_ImgButtonUpdateCancel(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonUpdateCancel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_LabelUpdateTip2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenClock
void ui_ScreenClock_screen_init(void);
void ui_event_ScreenClock(lv_event_t * e);
extern lv_obj_t * ui_ScreenClock;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_LabelClockHour;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_LabelClockMin;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_LabelClockSec;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
extern lv_obj_t * ui_ScreenWeather;
void ui_event_ImgButtonClose2(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose2;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_LabelWeatherLocation;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_ImageWeatherToday;
extern lv_obj_t * ui_LabelTempTpday;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_LabelWindText;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_LabelWind;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_LabelHBA;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_ContainerWeatherComp;
extern lv_obj_t * ui_LabelWeatherTime;
extern lv_obj_t * ui_ImageWeatherIcon;
extern lv_obj_t * ui_LabelTempValue;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_LabelHumValue;
extern lv_obj_t * ui_ContainerWeatherComp1;
extern lv_obj_t * ui_LabelWeatherTime2;
extern lv_obj_t * ui_ImageWeatherIcon2;
extern lv_obj_t * ui_LabelTempValue2;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_LabelHumValue2;
extern lv_obj_t * ui_ContainerWeatherComp2;
extern lv_obj_t * ui_LabelWeatherTime3;
extern lv_obj_t * ui_ImageWeatherIcon3;
extern lv_obj_t * ui_LabelTempValue3;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_LabelHumValue3;
extern lv_obj_t * ui_ContainerWeatherComp3;
extern lv_obj_t * ui_LabelWeatherTime4;
extern lv_obj_t * ui_ImageWeatherIcon4;
extern lv_obj_t * ui_LabelTempValue4;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_LabelHumValue4;
extern lv_obj_t * ui_ContainerWeatherComp4;
extern lv_obj_t * ui_LabelWeatherTime5;
extern lv_obj_t * ui_ImageWeatherIcon5;
extern lv_obj_t * ui_LabelTempValue5;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_LabelHumValue5;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAlarmClock
void ui_ScreenAlarmClock_screen_init(void);
void ui_event_ScreenAlarmClock(lv_event_t * e);
extern lv_obj_t * ui_ScreenAlarmClock;
void ui_event_ImgButtonClose3(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ContainerNoData;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_ContainerClockList;
void ui_event_ImgButtonAddClock(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonAddClock;
extern lv_obj_t * ui_ContainerSelectTime;
void ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonCancel(lv_event_t * e);
void ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonSure(lv_event_t * e);
extern lv_obj_t * ui_ContainerDialog;
void ui_event_ContainerDialog_Container25_Container27_ButtonCancelDelete(lv_event_t * e);
void ui_event_ContainerDialog_Container25_Container27_ButtonSureDelete(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAbout
void ui_ScreenAbout_screen_init(void);
extern lv_obj_t * ui_ScreenAbout;
void ui_event_ImgButtonClose4(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_LabelProjrctName;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_LabelProjrctVersion;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container14;
void ui_event_Container11(lv_event_t * e);
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Image12;
void ui_event_Container13(lv_event_t * e);
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Image13;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSetting
void ui_ScreenSetting_screen_init(void);
extern lv_obj_t * ui_ScreenSetting;
void ui_event_ImgButtonClose5(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_ContainerWifiSetting;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_LabelWiFiName;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_LabelWiFiPassword;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_LabelWiFiStatus;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_ContainerMqttSetting;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label21;
void ui_event_SwitchMQTT(lv_event_t * e);
extern lv_obj_t * ui_SwitchMQTT;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_LabelMqttUrl;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_LabelMqttPort;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_LabelMqttStatus;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWiFiSetting
void ui_ScreenWiFiSetting_screen_init(void);
void ui_event_ScreenWiFiSetting(lv_event_t * e);
extern lv_obj_t * ui_ScreenWiFiSetting;
void ui_event_ImgButtonClose6(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose6;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_RollerWiFiSelect;
void ui_event_ButtonWiFiSure(lv_event_t * e);
extern lv_obj_t * ui_ButtonWiFiSure;
extern lv_obj_t * ui_Label17;
void ui_event_ImageRefView(lv_event_t * e);
extern lv_obj_t * ui_ImageRefView;
extern lv_obj_t * ui_ContainerLoading2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWiFiPassword
void ui_ScreenWiFiPassword_screen_init(void);
void ui_event_ScreenWiFiPassword(lv_event_t * e);
extern lv_obj_t * ui_ScreenWiFiPassword;
void ui_event_ImgButtonClose7(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonClose7;
extern lv_obj_t * ui_Label27;
void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_selectWifiName;
void ui_event_ButtonWiFiSure2(lv_event_t * e);
extern lv_obj_t * ui_ButtonWiFiSure2;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_ContainerLoading3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen404
void ui_Screen404_screen_init(void);
extern lv_obj_t * ui_Screen404;
extern lv_obj_t * ui_Image18;
void ui_event_ImgButtonRestWfi(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonRestWfi;
extern lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenAlarm
void ui_ScreenAlarm_screen_init(void);
void ui_event_ScreenAlarm(lv_event_t * e);
extern lv_obj_t * ui_ScreenAlarm;
extern lv_obj_t * ui_ImageAlarm;
extern lv_obj_t * ui_Label30;
// CUSTOM VARIABLES

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_1371183408);    // assets/背景.png
LV_IMG_DECLARE(ui_img_944254084);    // assets/天气.png
LV_IMG_DECLARE(ui_img_1643258164);    // assets/天气2.png
LV_IMG_DECLARE(ui_img_480230510);    // assets/闹钟1.png
LV_IMG_DECLARE(ui_img_1208312639);    // assets/闹钟2.png
LV_IMG_DECLARE(ui_img_706350581);    // assets/表盘.png
LV_IMG_DECLARE(ui_img_131269067);    // assets/表盘2.png
LV_IMG_DECLARE(ui_img_1100213978);    // assets/设置1.png
LV_IMG_DECLARE(ui_img_372131849);    // assets/设置2.png
LV_IMG_DECLARE(ui_img_img_short_cut_bg_png);    // assets/img_short_cut_bg.png
LV_IMG_DECLARE(ui_img_53659793);    // assets/设置按钮selected.png
LV_IMG_DECLARE(ui_img_1668687438);    // assets/设置按钮.png
LV_IMG_DECLARE(ui_img_1593774066);    // assets/设置图标.png
LV_IMG_DECLARE(ui_img_2011621478);    // assets/闹钟按钮.png
LV_IMG_DECLARE(ui_img_512722608);    // assets/闹钟按钮selectedpng.png
LV_IMG_DECLARE(ui_img_2040269946);    // assets/闹钟图标.png
LV_IMG_DECLARE(ui_img_1828188889);    // assets/表盘按钮png.png
LV_IMG_DECLARE(ui_img_768181451);    // assets/表盘按钮selected.png
LV_IMG_DECLARE(ui_img_682944910);    // assets/表盘图标.png
LV_IMG_DECLARE(ui_img_1003441889);    // assets/天气按钮.png
LV_IMG_DECLARE(ui_img_762215214);    // assets/天气按钮selected.png
LV_IMG_DECLARE(ui_img_192374682);    // assets/天气多云图标.png
LV_IMG_DECLARE(ui_img_1457608042);    // assets/更新按钮.png
LV_IMG_DECLARE(ui_img_1986875052);    // assets/更新按钮secected.png
LV_IMG_DECLARE(ui_img_781433378);    // assets/更新图标.png
LV_IMG_DECLARE(ui_img_2041795965);    // assets/关于按钮.png
LV_IMG_DECLARE(ui_img_767529095);    // assets/关于按钮secected.png
LV_IMG_DECLARE(ui_img_1338268307);    // assets/关于图标.png
LV_IMG_DECLARE(ui_img_1256750410);    // assets/主页1.png
LV_IMG_DECLARE(ui_img_1373674343);    // assets/主页按钮selected.png
LV_IMG_DECLARE(ui_img_303547358);    // assets/主页图标.png
LV_IMG_DECLARE(ui_img_864073061);    // assets/页面关闭按钮.png
LV_IMG_DECLARE(ui_img_82540831);    // assets/页面关闭按钮2.png
LV_IMG_DECLARE(ui_img_42750357);    // assets/进度条背景3.png
LV_IMG_DECLARE(ui_img_1079156569);    // assets/更新按钮1.png
LV_IMG_DECLARE(ui_img_1807238698);    // assets/更新按钮2.png
LV_IMG_DECLARE(ui_img_1932134600);    // assets/取消按钮.png
LV_IMG_DECLARE(ui_img_1054422572);    // assets/取消按钮2.png
LV_IMG_DECLARE(ui_img_img_localtion_sign_png);    // assets/img_localtion_sign.png
LV_IMG_DECLARE(ui_img_qing80_png);    // assets/qing80.png
LV_IMG_DECLARE(ui_img_1860162427);    // assets/温度计.png
LV_IMG_DECLARE(ui_img_1974460379);    // assets/天气组件背景.png
LV_IMG_DECLARE(ui_img_wushuju60_png);    // assets/wushuju60.png
LV_IMG_DECLARE(ui_img_545021016);    // assets/湿度.png
LV_IMG_DECLARE(ui_img_xue60_png);    // assets/xue60.png
LV_IMG_DECLARE(ui_img_yintian60_png);    // assets/yintian60.png
LV_IMG_DECLARE(ui_img_yu60_png);    // assets/yu60.png
LV_IMG_DECLARE(ui_img_shachenbao60_png);    // assets/shachenbao60.png
LV_IMG_DECLARE(ui_img_1714809594);    // assets/新增列表 (1).png
LV_IMG_DECLARE(ui_img_add_png);    // assets/add.png
LV_IMG_DECLARE(ui_img_693056743);    // assets/add (2).png
LV_IMG_DECLARE(ui_img_679922800);    // assets/箭头.png
LV_IMG_DECLARE(ui_img_httpszjgsyjc_com_png);    // assets/httpszjgsyjc.com.png
LV_IMG_DECLARE(ui_img_img_wifi_setting_png);    // assets/img_wifi_setting.png
LV_IMG_DECLARE(ui_img_2110933116);    // assets/切换.png
LV_IMG_DECLARE(ui_img_508986726);    // assets/切换 (1).png
LV_IMG_DECLARE(ui_img_img_mqtt_setting_png);    // assets/img_mqtt_setting.png
LV_IMG_DECLARE(ui_img_1265361658);    // assets/加载.png
LV_IMG_DECLARE(ui_img_316677343);    // assets/加载 (2).png
LV_IMG_DECLARE(ui_img_696096750);    // assets/404图标.png
LV_IMG_DECLARE(ui_img_450751469);    // assets/报警,警报,报警灯,危险 (1).png
// 新增
LV_IMG_DECLARE(ui_img_qing60_png);  
LV_IMG_DECLARE(ui_img_dawu60_png);  
LV_IMG_DECLARE(ui_img_duoyun60_png);  
LV_IMG_DECLARE(ui_img_leizhenyu60_png);  
LV_IMG_DECLARE(ui_img_shachenbao80_png);  
LV_IMG_DECLARE(ui_img_wushuju80_png);  
LV_IMG_DECLARE(ui_img_xue80_png);  
LV_IMG_DECLARE(ui_img_yintian80_png);  
LV_IMG_DECLARE(ui_img_yu80_png);  
LV_IMG_DECLARE(ui_img_zhenyu80_png);  

// FONTS
LV_FONT_DECLARE(ui_font_Font100);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font22);
LV_FONT_DECLARE(ui_font_Font26);
LV_FONT_DECLARE(ui_font_Font80);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
