// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINERWEATHERCOMP_H
#define _UI_COMP_CONTAINERWEATHERCOMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerWeatherComp
#define UI_COMP_CONTAINERWEATHERCOMP_CONTAINERWEATHERCOMP 0
#define UI_COMP_CONTAINERWEATHERCOMP_LABELWEATHERTIME 1
#define UI_COMP_CONTAINERWEATHERCOMP_IMAGEWEATHERICON 2
#define UI_COMP_CONTAINERWEATHERCOMP_LABELTEMPVALUE 3
#define UI_COMP_CONTAINERWEATHERCOMP_IMAGE11 4
#define UI_COMP_CONTAINERWEATHERCOMP_LABELHUMVALUE 5
#define _UI_COMP_CONTAINERWEATHERCOMP_NUM 6
lv_obj_t * ui_ContainerWeatherComp_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
