// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_ContainerIcon_ImgButtonIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerIcon = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_callback(e);
    }
}

// COMPONENT ContainerIcon

lv_obj_t * ui_ContainerIcon_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerIcon;
    cui_ContainerIcon = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerIcon);
    lv_obj_set_width(cui_ContainerIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_ContainerIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_ContainerIcon, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerIcon, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerIcon, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_ContainerIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonIcon;
    cui_ImgButtonIcon = lv_imgbtn_create(cui_ContainerIcon);
    lv_imgbtn_set_src(cui_ImgButtonIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_944254084, NULL);
    lv_imgbtn_set_src(cui_ImgButtonIcon, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1643258164, NULL);
    lv_obj_set_width(cui_ImgButtonIcon, 60);
    lv_obj_set_height(cui_ImgButtonIcon, 60);
    lv_obj_set_align(cui_ImgButtonIcon, LV_ALIGN_CENTER);

    lv_obj_t * cui_LabelIconTitle;
    cui_LabelIconTitle = lv_label_create(cui_ContainerIcon);
    lv_obj_set_width(cui_LabelIconTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelIconTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelIconTitle, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelIconTitle, "天气");
    lv_obj_set_style_text_color(cui_LabelIconTitle, lv_color_hex(0xDEDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelIconTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelIconTitle, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_LabelIconTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_LabelIconTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_LabelIconTitle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_LabelIconTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERICON_NUM);
    children[UI_COMP_CONTAINERICON_CONTAINERICON] = cui_ContainerIcon;
    children[UI_COMP_CONTAINERICON_IMGBUTTONICON] = cui_ImgButtonIcon;
    children[UI_COMP_CONTAINERICON_LABELICONTITLE] = cui_LabelIconTitle;
    lv_obj_add_event_cb(cui_ContainerIcon, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerIcon, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ImgButtonIcon, ui_event_comp_ContainerIcon_ImgButtonIcon, LV_EVENT_ALL, children);
    ui_comp_ContainerIcon_create_hook(cui_ContainerIcon);
    return cui_ContainerIcon;
}

