// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_ContainerLoading_Image15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerLoading = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_READY) {
        loadingView_Animation(comp_ContainerLoading[UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_IMAGE15], 0);
    }
}

// COMPONENT ContainerLoading

lv_obj_t * ui_ContainerLoading_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerLoading;
    cui_ContainerLoading = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerLoading);
    lv_obj_set_width(cui_ContainerLoading, lv_pct(100));
    lv_obj_set_height(cui_ContainerLoading, lv_pct(100));
    lv_obj_set_align(cui_ContainerLoading, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerLoading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ContainerLoading, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerLoading, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerLoadingContent;
    cui_ContainerLoadingContent = lv_obj_create(cui_ContainerLoading);
    lv_obj_remove_style_all(cui_ContainerLoadingContent);
    lv_obj_set_width(cui_ContainerLoadingContent, 150);
    lv_obj_set_height(cui_ContainerLoadingContent, 150);
    lv_obj_set_align(cui_ContainerLoadingContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerLoadingContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerLoadingContent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerLoadingContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ContainerLoadingContent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerLoadingContent, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerLoadingContent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ContainerLoadingContent, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerLoadingContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image15;
    cui_Image15 = lv_img_create(cui_ContainerLoadingContent);
    lv_img_set_src(cui_Image15, &ui_img_316677343);
    lv_obj_set_width(cui_Image15, 60);
    lv_obj_set_height(cui_Image15, 60);
    lv_obj_set_align(cui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label26;
    cui_Label26 = lv_label_create(cui_ContainerLoadingContent);
    lv_obj_set_width(cui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label26, "加载中...");
    lv_obj_set_style_text_color(cui_Label26, lv_color_hex(0x11EA16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label26, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERLOADING_NUM);
    children[UI_COMP_CONTAINERLOADING_CONTAINERLOADING] = cui_ContainerLoading;
    children[UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT] = cui_ContainerLoadingContent;
    children[UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_IMAGE15] = cui_Image15;
    children[UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_LABEL26] = cui_Label26;
    lv_obj_add_event_cb(cui_ContainerLoading, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerLoading, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Image15, ui_event_comp_ContainerLoading_Image15, LV_EVENT_ALL, children);
    ui_comp_ContainerLoading_create_hook(cui_ContainerLoading);
    return cui_ContainerLoading;
}

