// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_COMP_HOOK_H
#define _SQUARELINE_PROJECT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_ContainerClockItem_create_hook(lv_obj_t * comp);
void ui_comp_ContainerDialog_create_hook(lv_obj_t * comp);
void ui_comp_ContainerIcon_create_hook(lv_obj_t * comp);
void ui_comp_ContainerLoading_create_hook(lv_obj_t * comp);
void ui_comp_ContainerSelectTime_create_hook(lv_obj_t * comp);
void ui_comp_ContainerShortCut_create_hook(lv_obj_t * comp);
void ui_comp_ContainerWeatherComp_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
