// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT ContainerClockItem

lv_obj_t * ui_ContainerClockItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerClockItem;
    cui_ContainerClockItem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerClockItem);
    lv_obj_set_height(cui_ContainerClockItem, 90);
    lv_obj_set_width(cui_ContainerClockItem, lv_pct(90));
    lv_obj_set_align(cui_ContainerClockItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerClockItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ContainerClockItem, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerClockItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ContainerClockItem, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerClockItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ContainerClockItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ContainerClockItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ContainerClockItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ContainerClockItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(cui_ContainerClockItem, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ContainerClockItem, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ContainerClockItem, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ContainerClockItem, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container10;
    cui_Container10 = lv_obj_create(cui_ContainerClockItem);
    lv_obj_remove_style_all(cui_Container10);
    lv_obj_set_height(cui_Container10, 80);
    lv_obj_set_width(cui_Container10, lv_pct(100));
    lv_obj_set_align(cui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Container10, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Container10, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container8;
    cui_Container8 = lv_obj_create(cui_Container10);
    lv_obj_remove_style_all(cui_Container8);
    lv_obj_set_width(cui_Container8, lv_pct(90));
    lv_obj_set_height(cui_Container8, lv_pct(100));
    lv_obj_set_align(cui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(cui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelClockTime;
    cui_LabelClockTime = lv_label_create(cui_Container8);
    lv_obj_set_width(cui_LabelClockTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelClockTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelClockTime, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelClockTime, "09:25");
    lv_obj_set_style_text_color(cui_LabelClockTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelClockTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelClockTime, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_SwitchClockOpen;
    cui_SwitchClockOpen = lv_switch_create(cui_Container8);
    lv_obj_set_width(cui_SwitchClockOpen, 50);
    lv_obj_set_height(cui_SwitchClockOpen, 25);
    lv_obj_set_align(cui_SwitchClockOpen, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERCLOCKITEM_NUM);
    children[UI_COMP_CONTAINERCLOCKITEM_CONTAINERCLOCKITEM] = cui_ContainerClockItem;
    children[UI_COMP_CONTAINERCLOCKITEM_CONTAINER10] = cui_Container10;
    children[UI_COMP_CONTAINERCLOCKITEM_CONTAINER10_CONTAINER8] = cui_Container8;
    children[UI_COMP_CONTAINERCLOCKITEM_CONTAINER10_CONTAINER8_LABELCLOCKTIME] = cui_LabelClockTime;
    children[UI_COMP_CONTAINERCLOCKITEM_CONTAINER10_CONTAINER8_SWITCHCLOCKOPEN] = cui_SwitchClockOpen;
    lv_obj_add_event_cb(cui_ContainerClockItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerClockItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerClockItem_create_hook(cui_ContainerClockItem);
    return cui_ContainerClockItem;
}

