// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT ContainerDialog

lv_obj_t * ui_ContainerDialog_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerDialog;
    cui_ContainerDialog = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerDialog);
    lv_obj_set_width(cui_ContainerDialog, lv_pct(100));
    lv_obj_set_height(cui_ContainerDialog, lv_pct(100));
    lv_obj_set_align(cui_ContainerDialog, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerDialog, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ContainerDialog, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerDialog, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container25;
    cui_Container25 = lv_obj_create(cui_ContainerDialog);
    lv_obj_remove_style_all(cui_Container25);
    lv_obj_set_width(cui_Container25, 300);
    lv_obj_set_height(cui_Container25, 200);
    lv_obj_set_align(cui_Container25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container25, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Container25, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Container25, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label33;
    cui_Label33 = lv_label_create(cui_Container25);
    lv_obj_set_width(cui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label33, 0);
    lv_obj_set_y(cui_Label33, 20);
    lv_obj_set_align(cui_Label33, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label33, "提示");
    lv_obj_set_style_text_color(cui_Label33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label33, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label34;
    cui_Label34 = lv_label_create(cui_Container25);
    lv_obj_set_width(cui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label34, 0);
    lv_obj_set_y(cui_Label34, -20);
    lv_obj_set_align(cui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label34, "确定要删除吗?");
    lv_obj_set_style_text_color(cui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label34, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container27;
    cui_Container27 = lv_obj_create(cui_Container25);
    lv_obj_remove_style_all(cui_Container27);
    lv_obj_set_height(cui_Container27, 65);
    lv_obj_set_width(cui_Container27, lv_pct(100));
    lv_obj_set_x(cui_Container27, 0);
    lv_obj_set_y(cui_Container27, -10);
    lv_obj_set_align(cui_Container27, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(cui_Container27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container27, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(cui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container27, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container27, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ButtonCancelDelete;
    cui_ButtonCancelDelete = lv_btn_create(cui_Container27);
    lv_obj_set_width(cui_ButtonCancelDelete, 120);
    lv_obj_set_height(cui_ButtonCancelDelete, 45);
    lv_obj_set_align(cui_ButtonCancelDelete, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonCancelDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonCancelDelete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ButtonCancelDelete, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonCancelDelete, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonCancelDelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ButtonCancelDelete, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ButtonCancelDelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonCancelDelete, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_ButtonCancelDelete, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(cui_ButtonCancelDelete, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ButtonCancelDelete, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_Label37;
    cui_Label37 = lv_label_create(cui_ButtonCancelDelete);
    lv_obj_set_width(cui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label37, "取消");
    lv_obj_set_style_text_color(cui_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label37, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ButtonSureDelete;
    cui_ButtonSureDelete = lv_btn_create(cui_Container27);
    lv_obj_set_width(cui_ButtonSureDelete, 120);
    lv_obj_set_height(cui_ButtonSureDelete, 45);
    lv_obj_set_align(cui_ButtonSureDelete, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonSureDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonSureDelete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ButtonSureDelete, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonSureDelete, lv_color_hex(0xFC0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonSureDelete, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ButtonSureDelete, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ButtonSureDelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonSureDelete, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonSureDelete, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ButtonSureDelete, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_Label35;
    cui_Label35 = lv_label_create(cui_ButtonSureDelete);
    lv_obj_set_width(cui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label35, "确定");
    lv_obj_set_style_text_color(cui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label35, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERDIALOG_NUM);
    children[UI_COMP_CONTAINERDIALOG_CONTAINERDIALOG] = cui_ContainerDialog;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25] = cui_Container25;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_LABEL33] = cui_Label33;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_LABEL34] = cui_Label34;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27] = cui_Container27;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27_BUTTONCANCELDELETE] = cui_ButtonCancelDelete;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27_BUTTONCANCELDELETE_LABEL37] = cui_Label37;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27_BUTTONSUREDELETE] = cui_ButtonSureDelete;
    children[UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27_BUTTONSUREDELETE_LABEL35] = cui_Label35;
    lv_obj_add_event_cb(cui_ContainerDialog, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerDialog, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerDialog_create_hook(cui_ContainerDialog);
    return cui_ContainerDialog;
}

