// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT ContainerSelectTime

lv_obj_t * ui_ContainerSelectTime_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerSelectTime;
    cui_ContainerSelectTime = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerSelectTime);
    lv_obj_set_width(cui_ContainerSelectTime, lv_pct(100));
    lv_obj_set_height(cui_ContainerSelectTime, lv_pct(100));
    lv_obj_set_align(cui_ContainerSelectTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerSelectTime, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerSelectTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerSelectTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ContainerSelectTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerSelectTime, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerSelectTime, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerAll;
    cui_ContainerAll = lv_obj_create(cui_ContainerSelectTime);
    lv_obj_remove_style_all(cui_ContainerAll);
    lv_obj_set_width(cui_ContainerAll, 340);
    lv_obj_set_height(cui_ContainerAll, 350);
    lv_obj_set_align(cui_ContainerAll, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerAll, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerAll, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerAll, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ContainerAll, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerAll, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerAll, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label9;
    cui_Label9 = lv_label_create(cui_ContainerAll);
    lv_obj_set_width(cui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label9, "时间选择");
    lv_label_set_recolor(cui_Label9, "true");
    lv_obj_set_style_text_color(cui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label9, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Label9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Label9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container4;
    cui_Container4 = lv_obj_create(cui_ContainerAll);
    lv_obj_remove_style_all(cui_Container4);
    lv_obj_set_height(cui_Container4, 200);
    lv_obj_set_width(cui_Container4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(cui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Container4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_RollerHour;
    cui_RollerHour = lv_roller_create(cui_Container4);
    lv_roller_set_options(cui_RollerHour,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(cui_RollerHour, 150);
    lv_obj_set_height(cui_RollerHour, 200);
    lv_obj_set_align(cui_RollerHour, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_RollerHour, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_RollerHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_RollerHour, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_RollerHour, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_RollerHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(cui_RollerHour, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_RollerHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_RollerHour, lv_color_hex(0x585858), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_RollerHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_t * cui_RollerMin;
    cui_RollerMin = lv_roller_create(cui_Container4);
    lv_roller_set_options(cui_RollerMin,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(cui_RollerMin, 30, LV_ANIM_OFF);
    lv_obj_set_width(cui_RollerMin, 150);
    lv_obj_set_height(cui_RollerMin, 200);
    lv_obj_set_align(cui_RollerMin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_RollerMin, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_RollerMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_RollerMin, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_RollerMin, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_RollerMin, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_RollerMin, lv_color_hex(0x585858), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_RollerMin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container6;
    cui_Container6 = lv_obj_create(cui_ContainerAll);
    lv_obj_remove_style_all(cui_Container6);
    lv_obj_set_height(cui_Container6, 71);
    lv_obj_set_width(cui_Container6, lv_pct(100));
    lv_obj_set_x(cui_Container6, 5);
    lv_obj_set_y(cui_Container6, -30);
    lv_obj_set_align(cui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_Container6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_Container6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_Container6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ButtonCancel;
    cui_ButtonCancel = lv_btn_create(cui_Container6);
    lv_obj_set_width(cui_ButtonCancel, 120);
    lv_obj_set_height(cui_ButtonCancel, 45);
    lv_obj_set_align(cui_ButtonCancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ButtonCancel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonCancel, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ButtonCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_ButtonCancel, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(cui_ButtonCancel, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ButtonCancel, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_Label10;
    cui_Label10 = lv_label_create(cui_ButtonCancel);
    lv_obj_set_width(cui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label10, "取消");
    lv_obj_set_style_text_color(cui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label10, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ButtonSure;
    cui_ButtonSure = lv_btn_create(cui_Container6);
    lv_obj_set_width(cui_ButtonSure, 120);
    lv_obj_set_height(cui_ButtonSure, 45);
    lv_obj_set_align(cui_ButtonSure, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ButtonSure, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonSure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ButtonSure, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonSure, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonSure, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_ButtonSure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_ButtonSure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_ButtonSure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ButtonSure, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ButtonSure, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_Label11;
    cui_Label11 = lv_label_create(cui_ButtonSure);
    lv_obj_set_width(cui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label11, "确定");
    lv_obj_set_style_text_color(cui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label11, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERSELECTTIME_NUM);
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERSELECTTIME] = cui_ContainerSelectTime;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL] = cui_ContainerAll;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_LABEL9] = cui_Label9;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER4] = cui_Container4;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER4_ROLLERHOUR] = cui_RollerHour;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER4_ROLLERMIN] = cui_RollerMin;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6] = cui_Container6;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6_BUTTONCANCEL] = cui_ButtonCancel;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6_BUTTONCANCEL_LABEL10] = cui_Label10;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6_BUTTONSURE] = cui_ButtonSure;
    children[UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6_BUTTONSURE_LABEL11] = cui_Label11;
    lv_obj_add_event_cb(cui_ContainerSelectTime, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerSelectTime, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerSelectTime_create_hook(cui_ContainerSelectTime);
    return cui_ContainerSelectTime;
}

