// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_event_comp_ContainerShortCut_ImgButtonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSetting, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenSetting_screen_init);
    }
}

void ui_event_comp_ContainerShortCut_ImgButtonClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAlarmClock, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenAlarmClock_screen_init);
    }
}

void ui_event_comp_ContainerShortCut_ImgButtonBiaoPan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenClock, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenClock_screen_init);
    }
}

void ui_event_comp_ContainerShortCut_ImgButtonWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenWeather_screen_init);
    }
}

void ui_event_comp_ContainerShortCut_ImgButtonUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenUpdate, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenUpdate_screen_init);
    }
}

void ui_event_comp_ContainerShortCut_ImgButtonAbour(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAbout, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ScreenAbout_screen_init);
    }
}

void ui_event_comp_ContainerShortCut_ImgButtonzhuye(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ContainerShortCut = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
    }
}

// COMPONENT ContainerShortCut

lv_obj_t * ui_ContainerShortCut_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerShortCut;
    cui_ContainerShortCut = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerShortCut);
    lv_obj_set_width(cui_ContainerShortCut, lv_pct(100));
    lv_obj_set_height(cui_ContainerShortCut, lv_pct(100));
    lv_obj_set_align(cui_ContainerShortCut, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ContainerShortCut, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_ContainerShortCut, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ContainerShortCut, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerShortCut, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image8;
    cui_Image8 = lv_img_create(cui_ContainerShortCut);
    lv_img_set_src(cui_Image8, &ui_img_img_short_cut_bg_png);
    lv_obj_set_width(cui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonSetting;
    cui_ImgButtonSetting = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_53659793, NULL);
    lv_imgbtn_set_src(cui_ImgButtonSetting, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1668687438, NULL);
    lv_obj_set_width(cui_ImgButtonSetting, 101);
    lv_obj_set_height(cui_ImgButtonSetting, 65);
    lv_obj_set_x(cui_ImgButtonSetting, 0);
    lv_obj_set_y(cui_ImgButtonSetting, -69);
    lv_obj_set_align(cui_ImgButtonSetting, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image2;
    cui_Image2 = lv_img_create(cui_ImgButtonSetting);
    lv_img_set_src(cui_Image2, &ui_img_1593774066);
    lv_obj_set_width(cui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonClock;
    cui_ImgButtonClock = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonClock, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2011621478, NULL);
    lv_imgbtn_set_src(cui_ImgButtonClock, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_512722608, NULL);
    lv_obj_set_width(cui_ImgButtonClock, 101);
    lv_obj_set_height(cui_ImgButtonClock, 66);
    lv_obj_set_x(cui_ImgButtonClock, 0);
    lv_obj_set_y(cui_ImgButtonClock, 66);
    lv_obj_set_align(cui_ImgButtonClock, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image3;
    cui_Image3 = lv_img_create(cui_ImgButtonClock);
    lv_img_set_src(cui_Image3, &ui_img_2040269946);
    lv_obj_set_width(cui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image3, 0);
    lv_obj_set_y(cui_Image3, 1);
    lv_obj_set_align(cui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonBiaoPan;
    cui_ImgButtonBiaoPan = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonBiaoPan, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1828188889, NULL);
    lv_imgbtn_set_src(cui_ImgButtonBiaoPan, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_768181451, NULL);
    lv_obj_set_width(cui_ImgButtonBiaoPan, 80);
    lv_obj_set_height(cui_ImgButtonBiaoPan, 89);
    lv_obj_set_x(cui_ImgButtonBiaoPan, -60);
    lv_obj_set_y(cui_ImgButtonBiaoPan, 43);
    lv_obj_set_align(cui_ImgButtonBiaoPan, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image4;
    cui_Image4 = lv_img_create(cui_ImgButtonBiaoPan);
    lv_img_set_src(cui_Image4, &ui_img_682944910);
    lv_obj_set_width(cui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image4, 0);
    lv_obj_set_y(cui_Image4, -6);
    lv_obj_set_align(cui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonWeather;
    cui_ImgButtonWeather = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonWeather, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1003441889, NULL);
    lv_imgbtn_set_src(cui_ImgButtonWeather, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_762215214, NULL);
    lv_obj_set_width(cui_ImgButtonWeather, 81);
    lv_obj_set_height(cui_ImgButtonWeather, 87);
    lv_obj_set_x(cui_ImgButtonWeather, -61);
    lv_obj_set_y(cui_ImgButtonWeather, -44);
    lv_obj_set_align(cui_ImgButtonWeather, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image5;
    cui_Image5 = lv_img_create(cui_ImgButtonWeather);
    lv_img_set_src(cui_Image5, &ui_img_192374682);
    lv_obj_set_width(cui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image5, 0);
    lv_obj_set_y(cui_Image5, 3);
    lv_obj_set_align(cui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonUpdate;
    cui_ImgButtonUpdate = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonUpdate, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1457608042, NULL);
    lv_imgbtn_set_src(cui_ImgButtonUpdate, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1986875052, NULL);
    lv_obj_set_width(cui_ImgButtonUpdate, 80);
    lv_obj_set_height(cui_ImgButtonUpdate, 87);
    lv_obj_set_x(cui_ImgButtonUpdate, 60);
    lv_obj_set_y(cui_ImgButtonUpdate, -45);
    lv_obj_set_align(cui_ImgButtonUpdate, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image6;
    cui_Image6 = lv_img_create(cui_ImgButtonUpdate);
    lv_img_set_src(cui_Image6, &ui_img_781433378);
    lv_obj_set_width(cui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image6, 1);
    lv_obj_set_y(cui_Image6, 4);
    lv_obj_set_align(cui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonAbour;
    cui_ImgButtonAbour = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonAbour, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2041795965, NULL);
    lv_imgbtn_set_src(cui_ImgButtonAbour, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_767529095, NULL);
    lv_obj_set_width(cui_ImgButtonAbour, 80);
    lv_obj_set_height(cui_ImgButtonAbour, 87);
    lv_obj_set_x(cui_ImgButtonAbour, 60);
    lv_obj_set_y(cui_ImgButtonAbour, 42);
    lv_obj_set_align(cui_ImgButtonAbour, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image7;
    cui_Image7 = lv_img_create(cui_ImgButtonAbour);
    lv_img_set_src(cui_Image7, &ui_img_1338268307);
    lv_obj_set_width(cui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image7, 0);
    lv_obj_set_y(cui_Image7, -5);
    lv_obj_set_align(cui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButtonzhuye;
    cui_ImgButtonzhuye = lv_imgbtn_create(cui_ContainerShortCut);
    lv_imgbtn_set_src(cui_ImgButtonzhuye, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1256750410, NULL);
    lv_imgbtn_set_src(cui_ImgButtonzhuye, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1373674343, NULL);
    lv_obj_set_width(cui_ImgButtonzhuye, 80);
    lv_obj_set_height(cui_ImgButtonzhuye, 80);
    lv_obj_set_align(cui_ImgButtonzhuye, LV_ALIGN_CENTER);

    lv_obj_t * cui_Image1;
    cui_Image1 = lv_img_create(cui_ImgButtonzhuye);
    lv_img_set_src(cui_Image1, &ui_img_303547358);
    lv_obj_set_width(cui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERSHORTCUT_NUM);
    children[UI_COMP_CONTAINERSHORTCUT_CONTAINERSHORTCUT] = cui_ContainerShortCut;
    children[UI_COMP_CONTAINERSHORTCUT_IMAGE8] = cui_Image8;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONSETTING] = cui_ImgButtonSetting;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONSETTING_IMAGE2] = cui_Image2;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONCLOCK] = cui_ImgButtonClock;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONCLOCK_IMAGE3] = cui_Image3;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONBIAOPAN] = cui_ImgButtonBiaoPan;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONBIAOPAN_IMAGE4] = cui_Image4;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONWEATHER] = cui_ImgButtonWeather;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONWEATHER_IMAGE5] = cui_Image5;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONUPDATE] = cui_ImgButtonUpdate;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONUPDATE_IMAGE6] = cui_Image6;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONABOUR] = cui_ImgButtonAbour;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONABOUR_IMAGE7] = cui_Image7;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONZHUYE] = cui_ImgButtonzhuye;
    children[UI_COMP_CONTAINERSHORTCUT_IMGBUTTONZHUYE_IMAGE1] = cui_Image1;
    lv_obj_add_event_cb(cui_ContainerShortCut, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerShortCut, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ImgButtonSetting, ui_event_comp_ContainerShortCut_ImgButtonSetting, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ImgButtonClock, ui_event_comp_ContainerShortCut_ImgButtonClock, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ImgButtonBiaoPan, ui_event_comp_ContainerShortCut_ImgButtonBiaoPan, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ImgButtonWeather, ui_event_comp_ContainerShortCut_ImgButtonWeather, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ImgButtonUpdate, ui_event_comp_ContainerShortCut_ImgButtonUpdate, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ImgButtonAbour, ui_event_comp_ContainerShortCut_ImgButtonAbour, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_ImgButtonzhuye, ui_event_comp_ContainerShortCut_ImgButtonzhuye, LV_EVENT_ALL, children);
    ui_comp_ContainerShortCut_create_hook(cui_ContainerShortCut);
    return cui_ContainerShortCut;
}

