// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_ContainerClockItem_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ContainerDialog_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ContainerIcon_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ContainerLoading_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ContainerSelectTime_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ContainerShortCut_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ContainerWeatherComp_create_hook(lv_obj_t * comp)
{
}
