// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINERICON_H
#define _UI_COMP_CONTAINERICON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerIcon
#define UI_COMP_CONTAINERICON_CONTAINERICON 0
#define UI_COMP_CONTAINERICON_IMGBUTTONICON 1
#define UI_COMP_CONTAINERICON_LABELICONTITLE 2
#define _UI_COMP_CONTAINERICON_NUM 3
lv_obj_t * ui_ContainerIcon_create(lv_obj_t * comp_parent);
void ui_event_comp_ContainerIcon_ImgButtonIcon(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
