// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT ContainerWeatherComp

lv_obj_t * ui_ContainerWeatherComp_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContainerWeatherComp;
    cui_ContainerWeatherComp = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerWeatherComp);
    lv_obj_set_width(cui_ContainerWeatherComp, 80);
    lv_obj_set_height(cui_ContainerWeatherComp, 260);
    lv_obj_set_align(cui_ContainerWeatherComp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ContainerWeatherComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(cui_ContainerWeatherComp, &ui_img_1974460379, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelWeatherTime;
    cui_LabelWeatherTime = lv_label_create(cui_ContainerWeatherComp);
    lv_obj_set_width(cui_LabelWeatherTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelWeatherTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelWeatherTime, 0);
    lv_obj_set_y(cui_LabelWeatherTime, -100);
    lv_obj_set_align(cui_LabelWeatherTime, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelWeatherTime, "16:00");
    lv_obj_set_style_text_color(cui_LabelWeatherTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelWeatherTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelWeatherTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImageWeatherIcon;
    cui_ImageWeatherIcon = lv_img_create(cui_ContainerWeatherComp);
    lv_obj_set_width(cui_ImageWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_ImageWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_ImageWeatherIcon, 0);
    lv_obj_set_y(cui_ImageWeatherIcon, -30);
    lv_obj_set_align(cui_ImageWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ImageWeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_ImageWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelTempValue;
    cui_LabelTempValue = lv_label_create(cui_ContainerWeatherComp);
    lv_obj_set_width(cui_LabelTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelTempValue, 0);
    lv_obj_set_y(cui_LabelTempValue, 30);
    lv_obj_set_align(cui_LabelTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelTempValue, "26℃");
    lv_obj_set_style_text_color(cui_LabelTempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelTempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(cui_LabelTempValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(cui_LabelTempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelTempValue, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image11;
    cui_Image11 = lv_img_create(cui_ContainerWeatherComp);
    lv_img_set_src(cui_Image11, &ui_img_545021016);
    lv_obj_set_width(cui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image11, -18);
    lv_obj_set_y(cui_Image11, 75);
    lv_obj_set_align(cui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelHumValue;
    cui_LabelHumValue = lv_label_create(cui_ContainerWeatherComp);
    lv_obj_set_width(cui_LabelHumValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelHumValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelHumValue, 8);
    lv_obj_set_y(cui_LabelHumValue, 75);
    lv_obj_set_align(cui_LabelHumValue, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelHumValue, "60%");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERWEATHERCOMP_NUM);
    children[UI_COMP_CONTAINERWEATHERCOMP_CONTAINERWEATHERCOMP] = cui_ContainerWeatherComp;
    children[UI_COMP_CONTAINERWEATHERCOMP_LABELWEATHERTIME] = cui_LabelWeatherTime;
    children[UI_COMP_CONTAINERWEATHERCOMP_IMAGEWEATHERICON] = cui_ImageWeatherIcon;
    children[UI_COMP_CONTAINERWEATHERCOMP_LABELTEMPVALUE] = cui_LabelTempValue;
    children[UI_COMP_CONTAINERWEATHERCOMP_IMAGE11] = cui_Image11;
    children[UI_COMP_CONTAINERWEATHERCOMP_LABELHUMVALUE] = cui_LabelHumValue;
    lv_obj_add_event_cb(cui_ContainerWeatherComp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerWeatherComp, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContainerWeatherComp_create_hook(cui_ContainerWeatherComp);
    return cui_ContainerWeatherComp;
}

