// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINERCLOCKITEM_H
#define _UI_COMP_CONTAINERCLOCKITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerClockItem
#define UI_COMP_CONTAINERCLOCKITEM_CONTAINERCLOCKITEM 0
#define UI_COMP_CONTAINERCLOCKITEM_CONTAINER10 1
#define UI_COMP_CONTAINERCLOCKITEM_CONTAINER10_CONTAINER8 2
#define UI_COMP_CONTAINERCLOCKITEM_CONTAINER10_CONTAINER8_LABELCLOCKTIME 3
#define UI_COMP_CONTAINERCLOCKITEM_CONTAINER10_CONTAINER8_SWITCHCLOCKOPEN 4
#define _UI_COMP_CONTAINERCLOCKITEM_NUM 5
lv_obj_t * ui_ContainerClockItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
