// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINERSHORTCUT_H
#define _UI_COMP_CONTAINERSHORTCUT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerShortCut
#define UI_COMP_CONTAINERSHORTCUT_CONTAINERSHORTCUT 0
#define UI_COMP_CONTAINERSHORTCUT_IMAGE8 1
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONSETTING 2
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONSETTING_IMAGE2 3
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONCLOCK 4
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONCLOCK_IMAGE3 5
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONBIAOPAN 6
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONBIAOPAN_IMAGE4 7
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONWEATHER 8
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONWEATHER_IMAGE5 9
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONUPDATE 10
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONUPDATE_IMAGE6 11
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONABOUR 12
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONABOUR_IMAGE7 13
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONZHUYE 14
#define UI_COMP_CONTAINERSHORTCUT_IMGBUTTONZHUYE_IMAGE1 15
#define _UI_COMP_CONTAINERSHORTCUT_NUM 16
lv_obj_t * ui_ContainerShortCut_create(lv_obj_t * comp_parent);
void ui_event_comp_ContainerShortCut_ImgButtonSetting(lv_event_t * e);
void ui_event_comp_ContainerShortCut_ImgButtonClock(lv_event_t * e);
void ui_event_comp_ContainerShortCut_ImgButtonBiaoPan(lv_event_t * e);
void ui_event_comp_ContainerShortCut_ImgButtonWeather(lv_event_t * e);
void ui_event_comp_ContainerShortCut_ImgButtonUpdate(lv_event_t * e);
void ui_event_comp_ContainerShortCut_ImgButtonAbour(lv_event_t * e);
void ui_event_comp_ContainerShortCut_ImgButtonzhuye(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
