// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINERLOADING_H
#define _UI_COMP_CONTAINERLOADING_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContainerLoading
#define UI_COMP_CONTAINERLOADING_CONTAINERLOADING 0
#define UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT 1
#define UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_IMAGE15 2
#define UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_LABEL26 3
#define _UI_COMP_CONTAINERLOADING_NUM 4
lv_obj_t * ui_ContainerLoading_create(lv_obj_t * comp_parent);
void ui_event_comp_ContainerLoading_Image15(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
