// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenShutCut_screen_init(void)
{
    ui_ScreenShutCut = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenShutCut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerShortCut = ui_ContainerShortCut_create(ui_ScreenShutCut);
    lv_obj_set_x(ui_ContainerShortCut, 0);
    lv_obj_set_y(ui_ContainerShortCut, 0);

}
