// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenAbout_screen_init(void)
{
    ui_ScreenAbout = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAbout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose4 = lv_imgbtn_create(ui_ScreenAbout);
    lv_imgbtn_set_src(ui_ImgButtonClose4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose4, 60);
    lv_obj_set_height(ui_ImgButtonClose4, 60);
    lv_obj_set_align(ui_ImgButtonClose4, LV_ALIGN_TOP_RIGHT);

    ui_Label7 = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "关于");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_ScreenAbout);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 70);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, 65);
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 64);
    lv_obj_set_width(ui_Container7, lv_pct(96));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container7, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "项目名称");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProjrctName = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_LabelProjrctName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProjrctName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelProjrctName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProjrctName, "4.0PAD");
    lv_obj_set_style_text_color(ui_LabelProjrctName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProjrctName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProjrctName, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelProjrctName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelProjrctName, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelProjrctName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelProjrctName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_ScreenAbout);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_height(ui_Container12, 70);
    lv_obj_set_width(ui_Container12, lv_pct(100));
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, 135);
    lv_obj_set_align(ui_Container12, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Container12);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_height(ui_Container9, 64);
    lv_obj_set_width(ui_Container9, lv_pct(96));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container9, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container9, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label13 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "固件版本");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProjrctVersion = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_LabelProjrctVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProjrctVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelProjrctVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProjrctVersion, "V1.0");
    lv_obj_set_style_text_color(ui_LabelProjrctVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProjrctVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProjrctVersion, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelProjrctVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelProjrctVersion, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelProjrctVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelProjrctVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -10);
    lv_obj_set_align(ui_Label12, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label12, "张家港市昱俊铖科技有限公司");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_ScreenAbout);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_height(ui_Container14, 70);
    lv_obj_set_width(ui_Container14, lv_pct(100));
    lv_obj_set_x(ui_Container14, 0);
    lv_obj_set_y(ui_Container14, 205);
    lv_obj_set_align(ui_Container14, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container11 = lv_obj_create(ui_Container14);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_height(ui_Container11, 64);
    lv_obj_set_width(ui_Container11, lv_pct(96));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Container11, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label15 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "官网地址");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_Container11);
    lv_img_set_src(ui_Image12, &ui_img_679922800);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container13 = lv_obj_create(ui_ScreenAbout);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, lv_pct(100));
    lv_obj_set_height(ui_Container13, lv_pct(100));
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container13, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_Container13);
    lv_img_set_src(ui_Image13, &ui_img_httpszjgsyjc_com_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image13, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonClose4, ui_event_ImgButtonClose4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container11, ui_event_Container11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container13, ui_event_Container13, LV_EVENT_ALL, NULL);

}
