// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenUpdate_screen_init(void)
{
    ui_ScreenUpdate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenUpdate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose = lv_imgbtn_create(ui_ScreenUpdate);
    lv_imgbtn_set_src(ui_ImgButtonClose, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose, 60);
    lv_obj_set_height(ui_ImgButtonClose, 60);
    lv_obj_set_align(ui_ImgButtonClose, LV_ALIGN_TOP_RIGHT);

    ui_LabelTitleUpdate = lv_label_create(ui_ScreenUpdate);
    lv_obj_set_width(ui_LabelTitleUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitleUpdate, 0);
    lv_obj_set_y(ui_LabelTitleUpdate, 15);
    lv_obj_set_align(ui_LabelTitleUpdate, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitleUpdate, "固件更新");
    lv_obj_set_style_text_font(ui_LabelTitleUpdate, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUpdateTip = lv_label_create(ui_ScreenUpdate);
    lv_obj_set_width(ui_LabelUpdateTip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUpdateTip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUpdateTip, 0);
    lv_obj_set_y(ui_LabelUpdateTip, 75);
    lv_obj_set_align(ui_LabelUpdateTip, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelUpdateTip, "下载成功后，将自动重启设备");
    lv_obj_set_style_text_color(ui_LabelUpdateTip, lv_color_hex(0x59E807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUpdateTip, 222, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUpdateTip, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_ScreenUpdate);
    lv_obj_set_width(ui_Arc1, 204);
    lv_obj_set_height(ui_Arc1, 204);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, 10);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 0);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_arc_set_rotation(ui_Arc1, 90);
    lv_obj_set_style_bg_img_src(ui_Arc1, &ui_img_42750357, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_dir(ui_Arc1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x59E807), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelProgress = lv_label_create(ui_ScreenUpdate);
    lv_obj_set_width(ui_LabelProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProgress, 0);
    lv_obj_set_y(ui_LabelProgress, 10);
    lv_obj_set_align(ui_LabelProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProgress, "0%");
    lv_obj_set_style_text_color(ui_LabelProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProgress, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonUpdate = lv_imgbtn_create(ui_ScreenUpdate);
    lv_imgbtn_set_src(ui_ImgButtonUpdate, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1079156569, NULL);
    lv_imgbtn_set_src(ui_ImgButtonUpdate, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1807238698, NULL);
    lv_obj_set_width(ui_ImgButtonUpdate, 160);
    lv_obj_set_height(ui_ImgButtonUpdate, 55);
    lv_obj_set_x(ui_ImgButtonUpdate, 0);
    lv_obj_set_y(ui_ImgButtonUpdate, -40);
    lv_obj_set_align(ui_ImgButtonUpdate, LV_ALIGN_BOTTOM_MID);

    ui_Label4 = lv_label_create(ui_ImgButtonUpdate);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "开始更新");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonUpdateCancel = lv_imgbtn_create(ui_ScreenUpdate);
    lv_imgbtn_set_src(ui_ImgButtonUpdateCancel, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1932134600, NULL);
    lv_imgbtn_set_src(ui_ImgButtonUpdateCancel, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1054422572, NULL);
    lv_obj_set_width(ui_ImgButtonUpdateCancel, 160);
    lv_obj_set_height(ui_ImgButtonUpdateCancel, 55);
    lv_obj_set_x(ui_ImgButtonUpdateCancel, 0);
    lv_obj_set_y(ui_ImgButtonUpdateCancel, -40);
    lv_obj_set_align(ui_ImgButtonUpdateCancel, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImgButtonUpdateCancel, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label1 = lv_label_create(ui_ImgButtonUpdateCancel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "取消更新");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUpdateTip2 = lv_label_create(ui_ScreenUpdate);
    lv_obj_set_width(ui_LabelUpdateTip2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUpdateTip2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUpdateTip2, 0);
    lv_obj_set_y(ui_LabelUpdateTip2, 110);
    lv_obj_set_align(ui_LabelUpdateTip2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelUpdateTip2, "下载过程中，请勿断电");
    lv_obj_set_style_text_color(ui_LabelUpdateTip2, lv_color_hex(0x59E807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUpdateTip2, 222, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUpdateTip2, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonClose, ui_event_ImgButtonClose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonUpdate, ui_event_ImgButtonUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonUpdateCancel, ui_event_ImgButtonUpdateCancel, LV_EVENT_ALL, NULL);

}
