// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenMain, &ui_img_1371183408, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTime = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_ContainerTime);
    lv_obj_set_width(ui_ContainerTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContainerTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContainerTime, 0);
    lv_obj_set_y(ui_ContainerTime, 80);
    lv_obj_set_align(ui_ContainerTime, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ContainerTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHour = lv_label_create(ui_ContainerTime);
    lv_obj_set_width(ui_LabelHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHour, "12");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHour, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &ui_font_Font100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaoHao = lv_label_create(ui_ContainerTime);
    lv_obj_set_width(ui_LabelMaoHao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaoHao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMaoHao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaoHao, ":");
    lv_obj_set_style_text_color(ui_LabelMaoHao, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaoHao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaoHao, &ui_font_Font100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMaoHao, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMaoHao, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMaoHao, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMaoHao, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMin = lv_label_create(ui_ContainerTime);
    lv_obj_set_width(ui_LabelMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMin, "30");
    lv_obj_set_style_text_color(ui_LabelMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMin, &ui_font_Font100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDate = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_ContainerDate);
    lv_obj_set_width(ui_ContainerDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContainerDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContainerDate, 0);
    lv_obj_set_y(ui_ContainerDate, 200);
    lv_obj_set_align(ui_ContainerDate, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ContainerDate, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerDate, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerDate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate = lv_label_create(ui_ContainerDate);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "5月26日");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &ui_font_Font26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDouHao = lv_label_create(ui_ContainerDate);
    lv_obj_set_width(ui_LabelDouHao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDouHao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDouHao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDouHao, "，");
    lv_obj_set_style_text_color(ui_LabelDouHao, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDouHao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDouHao, &ui_font_Font26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeek = lv_label_create(ui_ContainerDate);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeek, "星期一");
    lv_obj_set_style_text_color(ui_LabelWeek, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeek, &ui_font_Font26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerIconList = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_ContainerIconList);
    lv_obj_set_width(ui_ContainerIconList, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContainerIconList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContainerIconList, 0);
    lv_obj_set_y(ui_ContainerIconList, 100);
    lv_obj_set_align(ui_ContainerIconList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerIconList, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerIconList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerIconList, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerIcon = ui_ContainerIcon_create(ui_ContainerIconList);
    lv_obj_set_x(ui_ContainerIcon, 0);
    lv_obj_set_y(ui_ContainerIcon, 0);

    ui_ContainerIcon2 = ui_ContainerIcon_create(ui_ContainerIconList);
    lv_obj_set_x(ui_ContainerIcon2, 0);
    lv_obj_set_y(ui_ContainerIcon2, 0);
    lv_obj_set_style_pad_left(ui_ContainerIcon2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerIcon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerIcon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerIcon2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_imgbtn_set_src(ui_comp_get_child(ui_ContainerIcon2, UI_COMP_CONTAINERICON_IMGBUTTONICON), LV_IMGBTN_STATE_RELEASED,
                      NULL, &ui_img_480230510, NULL);
    lv_imgbtn_set_src(ui_comp_get_child(ui_ContainerIcon2, UI_COMP_CONTAINERICON_IMGBUTTONICON), LV_IMGBTN_STATE_PRESSED,
                      NULL, &ui_img_1208312639, NULL);

    lv_label_set_text(ui_comp_get_child(ui_ContainerIcon2, UI_COMP_CONTAINERICON_LABELICONTITLE), "闹钟");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_ContainerIcon2, UI_COMP_CONTAINERICON_LABELICONTITLE), &ui_font_Font16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerIcon3 = ui_ContainerIcon_create(ui_ContainerIconList);
    lv_obj_set_x(ui_ContainerIcon3, 0);
    lv_obj_set_y(ui_ContainerIcon3, 0);
    lv_obj_set_style_pad_left(ui_ContainerIcon3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerIcon3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerIcon3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerIcon3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_imgbtn_set_src(ui_comp_get_child(ui_ContainerIcon3, UI_COMP_CONTAINERICON_IMGBUTTONICON), LV_IMGBTN_STATE_RELEASED,
                      NULL, &ui_img_706350581, NULL);
    lv_imgbtn_set_src(ui_comp_get_child(ui_ContainerIcon3, UI_COMP_CONTAINERICON_IMGBUTTONICON), LV_IMGBTN_STATE_PRESSED,
                      NULL, &ui_img_131269067, NULL);

    lv_label_set_text(ui_comp_get_child(ui_ContainerIcon3, UI_COMP_CONTAINERICON_LABELICONTITLE), "表盘");

    ui_ContainerIcon4 = ui_ContainerIcon_create(ui_ContainerIconList);
    lv_obj_set_x(ui_ContainerIcon4, 0);
    lv_obj_set_y(ui_ContainerIcon4, 0);
    lv_obj_set_style_pad_left(ui_ContainerIcon4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerIcon4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerIcon4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerIcon4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_imgbtn_set_src(ui_comp_get_child(ui_ContainerIcon4, UI_COMP_CONTAINERICON_IMGBUTTONICON), LV_IMGBTN_STATE_RELEASED,
                      NULL, &ui_img_1100213978, NULL);
    lv_imgbtn_set_src(ui_comp_get_child(ui_ContainerIcon4, UI_COMP_CONTAINERICON_IMGBUTTONICON), LV_IMGBTN_STATE_PRESSED,
                      NULL, &ui_img_372131849, NULL);

    lv_label_set_text(ui_comp_get_child(ui_ContainerIcon4, UI_COMP_CONTAINERICON_LABELICONTITLE), "设置");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_ContainerIcon4, UI_COMP_CONTAINERICON_LABELICONTITLE), &ui_font_Font16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerShortCutMain = ui_ContainerShortCut_create(ui_ScreenMain);
    lv_obj_set_x(ui_ContainerShortCutMain, 0);
    lv_obj_set_y(ui_ContainerShortCutMain, 0);
    lv_obj_add_flag(ui_ContainerShortCutMain, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerIcon, UI_COMP_CONTAINERICON_IMGBUTTONICON),
                        ui_event_ContainerIcon_ImgButtonIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerIcon2, UI_COMP_CONTAINERICON_IMGBUTTONICON),
                        ui_event_ContainerIcon2_ImgButtonIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerIcon3, UI_COMP_CONTAINERICON_IMGBUTTONICON),
                        ui_event_ContainerIcon3_ImgButtonIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerIcon4, UI_COMP_CONTAINERICON_IMGBUTTONICON),
                        ui_event_ContainerIcon4_ImgButtonIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONSETTING),
                        ui_event_ContainerShortCutMain_ImgButtonSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONCLOCK),
                        ui_event_ContainerShortCutMain_ImgButtonClock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONBIAOPAN),
                        ui_event_ContainerShortCutMain_ImgButtonBiaoPan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONWEATHER),
                        ui_event_ContainerShortCutMain_ImgButtonWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONUPDATE),
                        ui_event_ContainerShortCutMain_ImgButtonUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONABOUR),
                        ui_event_ContainerShortCutMain_ImgButtonAbour, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerShortCutMain, UI_COMP_CONTAINERSHORTCUT_IMGBUTTONZHUYE),
                        ui_event_ContainerShortCutMain_ImgButtonzhuye, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ContainerShortCutMain, ui_event_ContainerShortCutMain_ContainerShortCut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenMain, ui_event_ScreenMain, LV_EVENT_ALL, NULL);

}
