// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen404_screen_init(void)
{
    ui_Screen404 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen404, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_Screen404);
    lv_img_set_src(ui_Image18, &ui_img_696096750);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image18, 0);
    lv_obj_set_y(ui_Image18, -30);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonRestWfi = lv_imgbtn_create(ui_Screen404);
    lv_imgbtn_set_src(ui_ImgButtonRestWfi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1079156569, NULL);
    lv_imgbtn_set_src(ui_ImgButtonRestWfi, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1807238698, NULL);
    lv_obj_set_width(ui_ImgButtonRestWfi, 160);
    lv_obj_set_height(ui_ImgButtonRestWfi, 55);
    lv_obj_set_x(ui_ImgButtonRestWfi, 0);
    lv_obj_set_y(ui_ImgButtonRestWfi, -80);
    lv_obj_set_align(ui_ImgButtonRestWfi, LV_ALIGN_BOTTOM_MID);

    ui_Label31 = lv_label_create(ui_ImgButtonRestWfi);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "重置WiFi");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonRestWfi, ui_event_ImgButtonRestWfi, LV_EVENT_ALL, NULL);

}
