// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenAlarmClock_screen_init(void)
{
    ui_ScreenAlarmClock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAlarmClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAlarmClock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAlarmClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose3 = lv_imgbtn_create(ui_ScreenAlarmClock);
    lv_imgbtn_set_src(ui_ImgButtonClose3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose3, 60);
    lv_obj_set_height(ui_ImgButtonClose3, 60);
    lv_obj_set_align(ui_ImgButtonClose3, LV_ALIGN_TOP_RIGHT);

    ui_Label2 = lv_label_create(ui_ScreenAlarmClock);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 20);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "设置闹钟");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerNoData = lv_obj_create(ui_ScreenAlarmClock);
    lv_obj_remove_style_all(ui_ContainerNoData);
    lv_obj_set_width(ui_ContainerNoData, 200);
    lv_obj_set_height(ui_ContainerNoData, 200);
    lv_obj_set_align(ui_ContainerNoData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerNoData, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerNoData, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerNoData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_ContainerNoData);
    lv_img_set_src(ui_Image17, &ui_img_1714809594);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_ContainerNoData);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "没有数据");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label32, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label32, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerClockList = lv_obj_create(ui_ScreenAlarmClock);
    lv_obj_remove_style_all(ui_ContainerClockList);
    lv_obj_set_width(ui_ContainerClockList, lv_pct(100));
    lv_obj_set_height(ui_ContainerClockList, lv_pct(87));
    lv_obj_set_align(ui_ContainerClockList, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ContainerClockList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerClockList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerClockList, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgButtonAddClock = lv_imgbtn_create(ui_ScreenAlarmClock);
    lv_imgbtn_set_src(ui_ImgButtonAddClock, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_png, NULL);
    lv_imgbtn_set_src(ui_ImgButtonAddClock, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_693056743, NULL);
    lv_obj_set_width(ui_ImgButtonAddClock, 40);
    lv_obj_set_height(ui_ImgButtonAddClock, 40);
    lv_obj_set_x(ui_ImgButtonAddClock, 25);
    lv_obj_set_y(ui_ImgButtonAddClock, 15);

    ui_ContainerSelectTime = ui_ContainerSelectTime_create(ui_ScreenAlarmClock);
    lv_obj_set_x(ui_ContainerSelectTime, 0);
    lv_obj_set_y(ui_ContainerSelectTime, 0);
    lv_obj_add_flag(ui_ContainerSelectTime, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ContainerDialog = ui_ContainerDialog_create(ui_ScreenAlarmClock);
    lv_obj_set_x(ui_ContainerDialog, 0);
    lv_obj_set_y(ui_ContainerDialog, 0);
    lv_obj_add_flag(ui_ContainerDialog, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ImgButtonClose3, ui_event_ImgButtonClose3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonAddClock, ui_event_ImgButtonAddClock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerSelectTime,
                                          UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6_BUTTONCANCEL),
                        ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerSelectTime,
                                          UI_COMP_CONTAINERSELECTTIME_CONTAINERALL_CONTAINER6_BUTTONSURE),
                        ui_event_ContainerSelectTime_ContainerAll_Container6_ButtonSure, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerDialog,
                                          UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27_BUTTONCANCELDELETE),
                        ui_event_ContainerDialog_Container25_Container27_ButtonCancelDelete, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_ContainerDialog,
                                          UI_COMP_CONTAINERDIALOG_CONTAINER25_CONTAINER27_BUTTONSUREDELETE),
                        ui_event_ContainerDialog_Container25_Container27_ButtonSureDelete, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenAlarmClock, ui_event_ScreenAlarmClock, LV_EVENT_ALL, NULL);

}
