// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSetting_screen_init(void)
{
    ui_ScreenSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose5 = lv_imgbtn_create(ui_ScreenSetting);
    lv_imgbtn_set_src(ui_ImgButtonClose5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose5, 60);
    lv_obj_set_height(ui_ImgButtonClose5, 60);
    lv_obj_set_align(ui_ImgButtonClose5, LV_ALIGN_TOP_RIGHT);

    ui_Label16 = lv_label_create(ui_ScreenSetting);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, 20);
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label16, "设置");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_ScreenSetting);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, lv_pct(96));
    lv_obj_set_height(ui_Container15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container15, 0);
    lv_obj_set_y(ui_Container15, 70);
    lv_obj_set_align(ui_Container15, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWifiSetting = lv_obj_create(ui_Container15);
    lv_obj_remove_style_all(ui_ContainerWifiSetting);
    lv_obj_set_height(ui_ContainerWifiSetting, 135);
    lv_obj_set_width(ui_ContainerWifiSetting, lv_pct(49));
    lv_obj_set_align(ui_ContainerWifiSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWifiSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerWifiSetting, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerWifiSetting, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerWifiSetting, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerWifiSetting, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ContainerWifiSetting, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container16 = lv_obj_create(ui_ContainerWifiSetting);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_height(ui_Container16, 25);
    lv_obj_set_width(ui_Container16, lv_pct(90));
    lv_obj_set_x(ui_Container16, 0);
    lv_obj_set_y(ui_Container16, 10);
    lv_obj_set_align(ui_Container16, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Container16);
    lv_img_set_src(ui_Image14, &ui_img_img_wifi_setting_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "WiFi设置");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_ContainerWifiSetting);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_height(ui_Container18, 25);
    lv_obj_set_width(ui_Container18, lv_pct(90));
    lv_obj_set_x(ui_Container18, 0);
    lv_obj_set_y(ui_Container18, 40);
    lv_obj_set_align(ui_Container18, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container18, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container18, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "账号:");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWiFiName = lv_label_create(ui_Container18);
    lv_obj_set_width(ui_LabelWiFiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWiFiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWiFiName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiName, "XIAOMI-CJF-204");
    lv_obj_set_style_text_color(ui_LabelWiFiName, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWiFiName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWiFiName, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWiFiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWiFiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWiFiName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_ContainerWifiSetting);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_height(ui_Container19, 25);
    lv_obj_set_width(ui_Container19, lv_pct(90));
    lv_obj_set_x(ui_Container19, 0);
    lv_obj_set_y(ui_Container19, 70);
    lv_obj_set_align(ui_Container19, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container19, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container19, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "密码:");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWiFiPassword = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_LabelWiFiPassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWiFiPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWiFiPassword, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiPassword, "a12345678");
    lv_obj_set_style_text_color(ui_LabelWiFiPassword, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWiFiPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWiFiPassword, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWiFiPassword, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWiFiPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWiFiPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWiFiPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_ContainerWifiSetting);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_height(ui_Container20, 25);
    lv_obj_set_width(ui_Container20, lv_pct(90));
    lv_obj_set_x(ui_Container20, 0);
    lv_obj_set_y(ui_Container20, 100);
    lv_obj_set_align(ui_Container20, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container20, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "状态:");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWiFiStatus = lv_label_create(ui_Container20);
    lv_obj_set_width(ui_LabelWiFiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWiFiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWiFiStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiStatus, "已连接");
    lv_obj_set_style_text_color(ui_LabelWiFiStatus, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWiFiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWiFiStatus, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWiFiStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWiFiStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWiFiStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWiFiStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_ContainerWifiSetting);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2110933116, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_508986726, NULL);
    lv_obj_set_width(ui_ImgButton1, 30);
    lv_obj_set_height(ui_ImgButton1, 30);
    lv_obj_set_x(ui_ImgButton1, -8);
    lv_obj_set_y(ui_ImgButton1, -8);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_BOTTOM_RIGHT);

    ui_ContainerMqttSetting = lv_obj_create(ui_Container15);
    lv_obj_remove_style_all(ui_ContainerMqttSetting);
    lv_obj_set_height(ui_ContainerMqttSetting, 135);
    lv_obj_set_width(ui_ContainerMqttSetting, lv_pct(49));
    lv_obj_set_align(ui_ContainerMqttSetting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMqttSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerMqttSetting, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerMqttSetting, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerMqttSetting, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerMqttSetting, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ContainerMqttSetting, 150, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container21 = lv_obj_create(ui_ContainerMqttSetting);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_height(ui_Container21, 25);
    lv_obj_set_width(ui_Container21, lv_pct(90));
    lv_obj_set_x(ui_Container21, 0);
    lv_obj_set_y(ui_Container21, 10);
    lv_obj_set_align(ui_Container21, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Container21);
    lv_img_set_src(ui_Image16, &ui_img_img_mqtt_setting_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Container21);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "MQTT设置");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label21, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchMQTT = lv_switch_create(ui_ContainerMqttSetting);
    lv_obj_set_width(ui_SwitchMQTT, 50);
    lv_obj_set_height(ui_SwitchMQTT, 25);
    lv_obj_set_x(ui_SwitchMQTT, -8);
    lv_obj_set_y(ui_SwitchMQTT, 8);
    lv_obj_set_align(ui_SwitchMQTT, LV_ALIGN_TOP_RIGHT);

    ui_Container22 = lv_obj_create(ui_ContainerMqttSetting);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_height(ui_Container22, 25);
    lv_obj_set_width(ui_Container22, lv_pct(90));
    lv_obj_set_x(ui_Container22, 0);
    lv_obj_set_y(ui_Container22, 40);
    lv_obj_set_align(ui_Container22, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "地址:");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMqttUrl = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_LabelMqttUrl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMqttUrl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMqttUrl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMqttUrl, "");
    lv_obj_set_style_text_color(ui_LabelMqttUrl, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMqttUrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMqttUrl, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMqttUrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMqttUrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMqttUrl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_ContainerMqttSetting);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_height(ui_Container23, 25);
    lv_obj_set_width(ui_Container23, lv_pct(90));
    lv_obj_set_x(ui_Container23, 0);
    lv_obj_set_y(ui_Container23, 70);
    lv_obj_set_align(ui_Container23, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container23, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container23, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "主题:");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMqttPort = lv_label_create(ui_Container23);
    lv_obj_set_width(ui_LabelMqttPort, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMqttPort, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMqttPort, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMqttPort, "");
    lv_obj_set_style_text_color(ui_LabelMqttPort, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMqttPort, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMqttPort, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMqttPort, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMqttPort, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMqttPort, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMqttPort, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container24 = lv_obj_create(ui_ContainerMqttSetting);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_height(ui_Container24, 25);
    lv_obj_set_width(ui_Container24, lv_pct(90));
    lv_obj_set_x(ui_Container24, 0);
    lv_obj_set_y(ui_Container24, 100);
    lv_obj_set_align(ui_Container24, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container24, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container24, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "状态:");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMqttStatus = lv_label_create(ui_Container24);
    lv_obj_set_width(ui_LabelMqttStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMqttStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMqttStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMqttStatus, "未连接");
    lv_obj_set_style_text_color(ui_LabelMqttStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMqttStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMqttStatus, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMqttStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMqttStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMqttStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMqttStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonClose5, ui_event_ImgButtonClose5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchMQTT, ui_event_SwitchMQTT, LV_EVENT_ALL, NULL);

}
