// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWiFiSetting_screen_init(void)
{
    ui_ScreenWiFiSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWiFiSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenWiFiSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWiFiSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose6 = lv_imgbtn_create(ui_ScreenWiFiSetting);
    lv_imgbtn_set_src(ui_ImgButtonClose6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose6, 60);
    lv_obj_set_height(ui_ImgButtonClose6, 60);
    lv_obj_set_align(ui_ImgButtonClose6, LV_ALIGN_TOP_RIGHT);

    ui_Label25 = lv_label_create(ui_ScreenWiFiSetting);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, 20);
    lv_obj_set_align(ui_Label25, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label25, "WiFi选择");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_ScreenWiFiSetting);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, lv_pct(96));
    lv_obj_set_height(ui_Container17, lv_pct(70));
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerWiFiSelect = lv_roller_create(ui_Container17);
    lv_roller_set_options(ui_RollerWiFiSelect, "", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerWiFiSelect, lv_pct(100));
    lv_obj_set_height(ui_RollerWiFiSelect, lv_pct(100));
    lv_obj_set_align(ui_RollerWiFiSelect, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerWiFiSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerWiFiSelect, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerWiFiSelect, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerWiFiSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerWiFiSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerWiFiSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RollerWiFiSelect, lv_color_hex(0x585858), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerWiFiSelect, 200, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ButtonWiFiSure = lv_btn_create(ui_ScreenWiFiSetting);
    lv_obj_set_height(ui_ButtonWiFiSure, 50);
    lv_obj_set_width(ui_ButtonWiFiSure, lv_pct(96));
    lv_obj_set_x(ui_ButtonWiFiSure, 0);
    lv_obj_set_y(ui_ButtonWiFiSure, -10);
    lv_obj_set_align(ui_ButtonWiFiSure, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonWiFiSure, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWiFiSure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonWiFiSure, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWiFiSure, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonWiFiSure, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWiFiSure, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonWiFiSure, 120, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label17 = lv_label_create(ui_ButtonWiFiSure);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "确定");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x11EA16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageRefView = lv_img_create(ui_ScreenWiFiSetting);
    lv_img_set_src(ui_ImageRefView, &ui_img_1265361658);
    lv_obj_set_width(ui_ImageRefView, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRefView, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageRefView, 10);
    lv_obj_set_y(ui_ImageRefView, 10);
    lv_obj_add_flag(ui_ImageRefView, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRefView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerLoading2 = ui_ContainerLoading_create(ui_ScreenWiFiSetting);
    lv_obj_set_x(ui_ContainerLoading2, 0);
    lv_obj_set_y(ui_ContainerLoading2, 0);
    lv_obj_clear_flag(ui_ContainerLoading2, LV_OBJ_FLAG_HIDDEN);      /// Flags

    lv_label_set_text(ui_comp_get_child(ui_ContainerLoading2, UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_LABEL26),
                      "扫描中...");

    lv_obj_add_event_cb(ui_ImgButtonClose6, ui_event_ImgButtonClose6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWiFiSure, ui_event_ButtonWiFiSure, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImageRefView, ui_event_ImageRefView, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenWiFiSetting, ui_event_ScreenWiFiSetting, LV_EVENT_ALL, NULL);

}
