// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenLogo_screen_init(void)
{
    ui_ScreenLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Imagelogo = lv_img_create(ui_ScreenLogo);
    lv_img_set_src(ui_Imagelogo, &ui_img_logo_png);
    lv_obj_set_width(ui_Imagelogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Imagelogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Imagelogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Imagelogo, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Imagelogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScreenLogo, ui_event_ScreenLogo, LV_EVENT_ALL, NULL);

}
