// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenClock_screen_init(void)
{
    ui_ScreenClock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenClock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ScreenClock);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -20);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelClockHour = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelClockHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClockHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelClockHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClockHour, "21");
    lv_obj_set_style_text_color(ui_LabelClockHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClockHour, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClockHour, &ui_font_Font80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, ":");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClockMin = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelClockMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClockMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelClockMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClockMin, "25");
    lv_obj_set_style_text_color(ui_LabelClockMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClockMin, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClockMin, &ui_font_Font80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, ":");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelClockSec = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelClockSec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClockSec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelClockSec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelClockSec, "20");
    lv_obj_set_style_text_color(ui_LabelClockSec, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelClockSec, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelClockSec, &ui_font_Font80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenClock, ui_event_ScreenClock, LV_EVENT_ALL, NULL);

}
