// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWiFiPassword_screen_init(void)
{
    ui_ScreenWiFiPassword = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWiFiPassword, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenWiFiPassword, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWiFiPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose7 = lv_imgbtn_create(ui_ScreenWiFiPassword);
    lv_imgbtn_set_src(ui_ImgButtonClose7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose7, 60);
    lv_obj_set_height(ui_ImgButtonClose7, 60);
    lv_obj_set_align(ui_ImgButtonClose7, LV_ALIGN_TOP_RIGHT);

    ui_Label27 = lv_label_create(ui_ScreenWiFiPassword);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, 20);
    lv_obj_set_align(ui_Label27, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label27, "WiFi密码");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaPassword = lv_textarea_create(ui_ScreenWiFiPassword);
    lv_obj_set_width(ui_TextAreaPassword, lv_pct(94));
    lv_obj_set_height(ui_TextAreaPassword, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_TextAreaPassword, 0);
    lv_obj_set_y(ui_TextAreaPassword, 130);
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "请输入密码");
    lv_textarea_set_one_line(ui_TextAreaPassword, true);
    lv_obj_set_style_text_color(ui_TextAreaPassword, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaPassword, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextAreaPassword, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaPassword, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaPassword, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextAreaPassword, lv_color_hex(0x808080),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaPassword, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_ScreenWiFiPassword);
    lv_obj_set_height(ui_Keyboard1, 200);
    lv_obj_set_width(ui_Keyboard1, lv_pct(96));
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, -5);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label29 = lv_label_create(ui_ScreenWiFiPassword);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 20);
    lv_obj_set_y(ui_Label29, 80);
    lv_label_set_text(ui_Label29, "WiFi名称:");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_selectWifiName = lv_label_create(ui_ScreenWiFiPassword);
    lv_obj_set_width(ui_selectWifiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_selectWifiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_selectWifiName, 120);
    lv_obj_set_y(ui_selectWifiName, 80);
    lv_label_set_text(ui_selectWifiName, "");
    lv_obj_set_style_text_color(ui_selectWifiName, lv_color_hex(0x16F30F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_selectWifiName, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_selectWifiName, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonWiFiSure2 = lv_btn_create(ui_ScreenWiFiPassword);
    lv_obj_set_height(ui_ButtonWiFiSure2, 50);
    lv_obj_set_width(ui_ButtonWiFiSure2, lv_pct(94));
    lv_obj_set_x(ui_ButtonWiFiSure2, 0);
    lv_obj_set_y(ui_ButtonWiFiSure2, 200);
    lv_obj_set_align(ui_ButtonWiFiSure2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonWiFiSure2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWiFiSure2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonWiFiSure2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWiFiSure2, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonWiFiSure2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonWiFiSure2, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonWiFiSure2, 120, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label28 = lv_label_create(ui_ButtonWiFiSure2);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "确定");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x11EA16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label28, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLoading3 = ui_ContainerLoading_create(ui_ScreenWiFiPassword);
    lv_obj_set_x(ui_ContainerLoading3, 0);
    lv_obj_set_y(ui_ContainerLoading3, 0);
    lv_obj_add_flag(ui_ContainerLoading3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_label_set_text(ui_comp_get_child(ui_ContainerLoading3, UI_COMP_CONTAINERLOADING_CONTAINERLOADINGCONTENT_LABEL26),
                      "初始化中...");

    lv_obj_add_event_cb(ui_ImgButtonClose7, ui_event_ImgButtonClose7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWiFiSure2, ui_event_ButtonWiFiSure2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenWiFiPassword, ui_event_ScreenWiFiPassword, LV_EVENT_ALL, NULL);

}
