// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenWeather, lv_color_hex(0x506892), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonClose2 = lv_imgbtn_create(ui_ScreenWeather);
    lv_imgbtn_set_src(ui_ImgButtonClose2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_864073061, NULL);
    lv_imgbtn_set_src(ui_ImgButtonClose2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_82540831, NULL);
    lv_obj_set_width(ui_ImgButtonClose2, 60);
    lv_obj_set_height(ui_ImgButtonClose2, 60);
    lv_obj_set_align(ui_ImgButtonClose2, LV_ALIGN_TOP_RIGHT);

    ui_Image9 = lv_img_create(ui_ScreenWeather);
    lv_img_set_src(ui_Image9, &ui_img_img_localtion_sign_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image9, 20);
    lv_obj_set_y(ui_Image9, 30);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatherLocation = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelWeatherLocation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherLocation, 50);
    lv_obj_set_y(ui_LabelWeatherLocation, 30);
    lv_label_set_text(ui_LabelWeatherLocation, "张家港市");
    lv_obj_set_style_text_color(ui_LabelWeatherLocation, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherLocation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherLocation, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ScreenWeather);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 80);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 70);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWeatherToday = lv_img_create(ui_Container2);
    lv_img_set_src(ui_ImageWeatherToday, &ui_img_qing80_png);
    lv_obj_set_width(ui_ImageWeatherToday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherToday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageWeatherToday, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherToday, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherToday, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempTpday = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LabelTempTpday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempTpday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempTpday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempTpday, "26");
    lv_obj_set_style_text_color(ui_LabelTempTpday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempTpday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempTpday, &ui_font_Font80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelTempTpday, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelTempTpday, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelTempTpday, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelTempTpday, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "℃");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image10, &ui_img_1860162427);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 190);
    lv_obj_set_height(ui_Container8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container8, 3);
    lv_obj_set_y(ui_Container8, 0);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label36, "风速:");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label36, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindText = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_LabelWindText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindText, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelWindText, "4-5级 8.0~10.7m/s");
    lv_obj_set_style_text_color(ui_LabelWindText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindText, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWindText, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWindText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWindText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWindText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label38, "风向:");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label38, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label38, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWind = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_LabelWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWind, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelWind, "东南西北风");
    lv_obj_set_style_text_color(ui_LabelWind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWind, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWind, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWind, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label39, "气压:");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label39, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label39, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHBA = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_LabelHBA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHBA, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelHBA, "1003.3 hPa");
    lv_obj_set_style_text_color(ui_LabelHBA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHBA, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelHBA, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelHBA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelHBA, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelHBA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_ScreenWeather);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(90));
    lv_obj_set_height(ui_Container3, lv_pct(65));
    lv_obj_set_align(ui_Container3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWeatherComp = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ContainerWeatherComp);
    lv_obj_set_width(ui_ContainerWeatherComp, 80);
    lv_obj_set_height(ui_ContainerWeatherComp, 260);
    lv_obj_set_align(ui_ContainerWeatherComp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeatherComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ContainerWeatherComp, &ui_img_1974460379, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTime = lv_label_create(ui_ContainerWeatherComp);
    lv_obj_set_width(ui_LabelWeatherTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTime, 0);
    lv_obj_set_y(ui_LabelWeatherTime, -100);
    lv_obj_set_align(ui_LabelWeatherTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherTime, "星期一");
    lv_obj_set_style_text_color(ui_LabelWeatherTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherTime, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon = lv_img_create(ui_ContainerWeatherComp);
    lv_img_set_src(ui_ImageWeatherIcon, &ui_img_wushuju60_png);
    lv_obj_set_width(ui_ImageWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon, 0);
    lv_obj_set_y(ui_ImageWeatherIcon, -30);
    lv_obj_set_align(ui_ImageWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempValue = lv_label_create(ui_ContainerWeatherComp);
    lv_obj_set_width(ui_LabelTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempValue, 0);
    lv_obj_set_y(ui_LabelTempValue, 30);
    lv_obj_set_align(ui_LabelTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempValue, "26℃");
    lv_obj_set_style_text_color(ui_LabelTempValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempValue, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_ContainerWeatherComp);
    lv_img_set_src(ui_Image11, &ui_img_545021016);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -18);
    lv_obj_set_y(ui_Image11, 75);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumValue = lv_label_create(ui_ContainerWeatherComp);
    lv_obj_set_width(ui_LabelHumValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumValue, 8);
    lv_obj_set_y(ui_LabelHumValue, 75);
    lv_obj_set_align(ui_LabelHumValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumValue, "60%");

    ui_ContainerWeatherComp1 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ContainerWeatherComp1);
    lv_obj_set_width(ui_ContainerWeatherComp1, 80);
    lv_obj_set_height(ui_ContainerWeatherComp1, 260);
    lv_obj_set_align(ui_ContainerWeatherComp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeatherComp1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ContainerWeatherComp1, &ui_img_1974460379, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTime2 = lv_label_create(ui_ContainerWeatherComp1);
    lv_obj_set_width(ui_LabelWeatherTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTime2, 0);
    lv_obj_set_y(ui_LabelWeatherTime2, -100);
    lv_obj_set_align(ui_LabelWeatherTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherTime2, "星期二");
    lv_obj_set_style_text_color(ui_LabelWeatherTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherTime2, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon2 = lv_img_create(ui_ContainerWeatherComp1);
    lv_img_set_src(ui_ImageWeatherIcon2, &ui_img_xue60_png);
    lv_obj_set_width(ui_ImageWeatherIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon2, 0);
    lv_obj_set_y(ui_ImageWeatherIcon2, -30);
    lv_obj_set_align(ui_ImageWeatherIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempValue2 = lv_label_create(ui_ContainerWeatherComp1);
    lv_obj_set_width(ui_LabelTempValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempValue2, 0);
    lv_obj_set_y(ui_LabelTempValue2, 30);
    lv_obj_set_align(ui_LabelTempValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempValue2, "26℃");
    lv_obj_set_style_text_color(ui_LabelTempValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempValue2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempValue2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempValue2, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image20 = lv_img_create(ui_ContainerWeatherComp1);
    lv_img_set_src(ui_Image20, &ui_img_545021016);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20, -18);
    lv_obj_set_y(ui_Image20, 75);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumValue2 = lv_label_create(ui_ContainerWeatherComp1);
    lv_obj_set_width(ui_LabelHumValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumValue2, 8);
    lv_obj_set_y(ui_LabelHumValue2, 75);
    lv_obj_set_align(ui_LabelHumValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumValue2, "60%");

    ui_ContainerWeatherComp2 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ContainerWeatherComp2);
    lv_obj_set_width(ui_ContainerWeatherComp2, 80);
    lv_obj_set_height(ui_ContainerWeatherComp2, 260);
    lv_obj_set_align(ui_ContainerWeatherComp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeatherComp2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ContainerWeatherComp2, &ui_img_1974460379, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTime3 = lv_label_create(ui_ContainerWeatherComp2);
    lv_obj_set_width(ui_LabelWeatherTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTime3, 0);
    lv_obj_set_y(ui_LabelWeatherTime3, -100);
    lv_obj_set_align(ui_LabelWeatherTime3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherTime3, "星期三");
    lv_obj_set_style_text_color(ui_LabelWeatherTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherTime3, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon3 = lv_img_create(ui_ContainerWeatherComp2);
    lv_img_set_src(ui_ImageWeatherIcon3, &ui_img_yintian60_png);
    lv_obj_set_width(ui_ImageWeatherIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon3, 0);
    lv_obj_set_y(ui_ImageWeatherIcon3, -30);
    lv_obj_set_align(ui_ImageWeatherIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempValue3 = lv_label_create(ui_ContainerWeatherComp2);
    lv_obj_set_width(ui_LabelTempValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempValue3, 0);
    lv_obj_set_y(ui_LabelTempValue3, 30);
    lv_obj_set_align(ui_LabelTempValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempValue3, "26℃");
    lv_obj_set_style_text_color(ui_LabelTempValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempValue3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempValue3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempValue3, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_img_create(ui_ContainerWeatherComp2);
    lv_img_set_src(ui_Image21, &ui_img_545021016);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, -18);
    lv_obj_set_y(ui_Image21, 75);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumValue3 = lv_label_create(ui_ContainerWeatherComp2);
    lv_obj_set_width(ui_LabelHumValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumValue3, 8);
    lv_obj_set_y(ui_LabelHumValue3, 75);
    lv_obj_set_align(ui_LabelHumValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumValue3, "60%");

    ui_ContainerWeatherComp3 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ContainerWeatherComp3);
    lv_obj_set_width(ui_ContainerWeatherComp3, 80);
    lv_obj_set_height(ui_ContainerWeatherComp3, 260);
    lv_obj_set_align(ui_ContainerWeatherComp3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeatherComp3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ContainerWeatherComp3, &ui_img_1974460379, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTime4 = lv_label_create(ui_ContainerWeatherComp3);
    lv_obj_set_width(ui_LabelWeatherTime4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTime4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTime4, 0);
    lv_obj_set_y(ui_LabelWeatherTime4, -100);
    lv_obj_set_align(ui_LabelWeatherTime4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherTime4, "星期四");
    lv_obj_set_style_text_color(ui_LabelWeatherTime4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherTime4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherTime4, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon4 = lv_img_create(ui_ContainerWeatherComp3);
    lv_img_set_src(ui_ImageWeatherIcon4, &ui_img_yu60_png);
    lv_obj_set_width(ui_ImageWeatherIcon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon4, 0);
    lv_obj_set_y(ui_ImageWeatherIcon4, -30);
    lv_obj_set_align(ui_ImageWeatherIcon4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempValue4 = lv_label_create(ui_ContainerWeatherComp3);
    lv_obj_set_width(ui_LabelTempValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempValue4, 0);
    lv_obj_set_y(ui_LabelTempValue4, 30);
    lv_obj_set_align(ui_LabelTempValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempValue4, "26℃");
    lv_obj_set_style_text_color(ui_LabelTempValue4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempValue4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempValue4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempValue4, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image22 = lv_img_create(ui_ContainerWeatherComp3);
    lv_img_set_src(ui_Image22, &ui_img_545021016);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, -18);
    lv_obj_set_y(ui_Image22, 75);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumValue4 = lv_label_create(ui_ContainerWeatherComp3);
    lv_obj_set_width(ui_LabelHumValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumValue4, 8);
    lv_obj_set_y(ui_LabelHumValue4, 75);
    lv_obj_set_align(ui_LabelHumValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumValue4, "60%");

    ui_ContainerWeatherComp4 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_ContainerWeatherComp4);
    lv_obj_set_width(ui_ContainerWeatherComp4, 80);
    lv_obj_set_height(ui_ContainerWeatherComp4, 260);
    lv_obj_set_align(ui_ContainerWeatherComp4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeatherComp4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ContainerWeatherComp4, &ui_img_1974460379, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTime5 = lv_label_create(ui_ContainerWeatherComp4);
    lv_obj_set_width(ui_LabelWeatherTime5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTime5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTime5, 0);
    lv_obj_set_y(ui_LabelWeatherTime5, -100);
    lv_obj_set_align(ui_LabelWeatherTime5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherTime5, "星期五");
    lv_obj_set_style_text_color(ui_LabelWeatherTime5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeatherTime5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeatherTime5, &ui_font_Font16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeatherIcon5 = lv_img_create(ui_ContainerWeatherComp4);
    lv_img_set_src(ui_ImageWeatherIcon5, &ui_img_shachenbao60_png);
    lv_obj_set_width(ui_ImageWeatherIcon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeatherIcon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeatherIcon5, 0);
    lv_obj_set_y(ui_ImageWeatherIcon5, -30);
    lv_obj_set_align(ui_ImageWeatherIcon5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeatherIcon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeatherIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempValue5 = lv_label_create(ui_ContainerWeatherComp4);
    lv_obj_set_width(ui_LabelTempValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempValue5, 0);
    lv_obj_set_y(ui_LabelTempValue5, 30);
    lv_obj_set_align(ui_LabelTempValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempValue5, "26℃");
    lv_obj_set_style_text_color(ui_LabelTempValue5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempValue5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempValue5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempValue5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempValue5, &ui_font_Font22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_ContainerWeatherComp4);
    lv_img_set_src(ui_Image23, &ui_img_545021016);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, -18);
    lv_obj_set_y(ui_Image23, 75);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHumValue5 = lv_label_create(ui_ContainerWeatherComp4);
    lv_obj_set_width(ui_LabelHumValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumValue5, 8);
    lv_obj_set_y(ui_LabelHumValue5, 75);
    lv_obj_set_align(ui_LabelHumValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumValue5, "60%");

    lv_obj_add_event_cb(ui_ImgButtonClose2, ui_event_ImgButtonClose2, LV_EVENT_ALL, NULL);

}
